[package]
resolver = "2"
version = "0.1.0"
authors = ["Doug Chimento <dchimento@gmail.com>"]
repository = "https://github.com/dougEfish/fireblocks-sdk"
license = "MIT"
edition = "2021"
rust-version = "1.76"
name = "fireblocks-sdk"

[lib]
name = "fireblocks_sdk"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[features]
default = ["native"]
native = ["reqwest"]
wasm = ["wasm-bindgen", "js-sys", "wasm-bindgen-futures", "reqwest_wasi", "web-sys"]

[lints.rust]
unsafe_code = "forbid"
#dead_code = "allow"

[lints.clippy]
enum_glob_use = "deny"
pedantic = "deny"
nursery = "deny"
unwrap_used = "deny"
module_name_repetitions = "allow"
future_not_send = "allow"
must_use_candidate = "allow"
#dead_code = "allow"

[dependencies]
trait-variant = { version = "0.1.0"}
serde_json = "1"
serde = "1.0.195"
serde_derive = { version = "1"}
jsonwebtoken = "9"
reqwest = { version = "0.11", default-features = true, features = ["json"], optional = true }
tokio = { version = "1", features = ["full", "tracing"] }
thiserror = "1"
bigdecimal = { version = "^0.3", features = ["serde"] }
url = "2"
chrono = { version = "0.4", default-features = true, features = ["serde", "wasmbind"] }
pretty_assertions = "1.4.0"
log = { version = "0.4" , features = ["std", "serde", "kv_unstable", "kv_unstable_serde"] }
tracing = {  version = "0.1" }
tracing-log = {version = "0.2" }
tracing-error = { version = "0.2" }
tracing-subscriber = { version = "0.3", features = ["env-filter", "serde"] }
tokio-util = { version = "0.7", features = ["rt"] }
futures = { version = "0.3" }
human-panic = { version = "1.2" }
sha2 = "0.10"
rand = "0.8"

### WASM #####
wasm-bindgen = { version = "0.2", features = ["serde-serialize"], optional = true }
js-sys = { version = "0.3", optional = true }
wasm-bindgen-futures = {version = "0.4", optional = true}

[dependencies.reqwest_wasi]
version = "0.11"
optional = true

[dependencies.web-sys]
version = "0.3.4"
features = [
    'Headers',
    'Request',
    'RequestInit',
    'RequestMode',
    'Response',
    'Window',
]
optional = true


[dev-dependencies]
#reqwest = { version = "0.11.22", default-features = false, features = ["json", "rustls"] }
tokio = { version = "1", features = ["macros", "rt"] }
rstest = { version = "0.18" }
color-eyre = { version = "0.6" }
lazy_static = "1.4.0"
dotenvy = { version = "0.15" }