// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    super::{Error, configuration},
    crate::{
        apis::{ContentType, ResponseContent},
        models,
    },
    async_trait::async_trait,
    reqwest,
    serde::{Deserialize, Serialize, de::Error as _},
    std::sync::Arc,
};

#[async_trait]
pub trait ConnectedAccountsBetaApi: Send + Sync {
    /// GET /connected_accounts/{accountId}
    ///
    /// Retrieve detailed information about a specific connected account by ID.
    /// **Note:** This endpoint is currently in beta and might be subject to
    /// changes.
    async fn get_connected_account(
        &self,
        params: GetConnectedAccountParams,
    ) -> Result<models::ConnectedSingleAccountResponse, Error<GetConnectedAccountError>>;

    /// GET /connected_accounts/{accountId}/balances
    ///
    /// Retrieve current asset balances for a specific connected account as a
    /// flat list (one row per `assetId`, `balanceType`).  **Note:** This
    /// endpoint is currently in beta and might be subject to changes.
    async fn get_connected_account_balances(
        &self,
        params: GetConnectedAccountBalancesParams,
    ) -> Result<models::ConnectedAccountBalancesResponse, Error<GetConnectedAccountBalancesError>>;

    /// GET /connected_accounts/{accountId}/rates
    ///
    /// Retrieve current exchange rates for converting between specific assets
    /// in a connected account.  **Note:** This endpoint is currently in beta
    /// and might be subject to changes.
    async fn get_connected_account_rates(
        &self,
        params: GetConnectedAccountRatesParams,
    ) -> Result<models::ConnectedAccountRateResponse, Error<GetConnectedAccountRatesError>>;

    /// GET /connected_accounts/{accountId}/manifest/capabilities/trading/pairs
    ///
    /// Retrieve all asset trading pairs supported by a specific connected
    /// account, including the pair type (`quote`, `market`, `onOffRamp`).
    /// **Note:** This endpoint is currently in beta and might be subject to
    /// changes.
    async fn get_connected_account_trading_pairs(
        &self,
        params: GetConnectedAccountTradingPairsParams,
    ) -> Result<
        models::ConnectedAccountTradingPairsResponse,
        Error<GetConnectedAccountTradingPairsError>,
    >;

    /// GET /connected_accounts
    ///
    /// Returns all connected accounts.  **Note:** This endpoint is currently in
    /// beta and might be subject to changes.
    async fn get_connected_accounts(
        &self,
        params: GetConnectedAccountsParams,
    ) -> Result<models::ConnectedAccountsResponse, Error<GetConnectedAccountsError>>;
}

pub struct ConnectedAccountsBetaApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl ConnectedAccountsBetaApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

/// struct for passing parameters to the method
/// [`ConnectedAccountsBetaApi::get_connected_account`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct GetConnectedAccountParams {
    /// The ID of the account to fetch.
    pub account_id: String,
}

/// struct for passing parameters to the method
/// [`ConnectedAccountsBetaApi::get_connected_account_balances`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct GetConnectedAccountBalancesParams {
    /// The ID of the account to fetch balances for.
    pub account_id: String,
    /// Page size for pagination.
    pub page_size: Option<u16>,
    /// Page cursor for pagination.
    pub page_cursor: Option<String>,
}

/// struct for passing parameters to the method
/// [`ConnectedAccountsBetaApi::get_connected_account_rates`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct GetConnectedAccountRatesParams {
    /// The ID of the account to fetch rates for.
    pub account_id: String,
    /// The ID of the asset to fetch rates for.
    pub base_asset_id: String,
    /// The ID of the asset to get the rates nominally.
    pub quote_asset_id: String,
}

/// struct for passing parameters to the method
/// [`ConnectedAccountsBetaApi::get_connected_account_trading_pairs`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct GetConnectedAccountTradingPairsParams {
    /// The ID of the account to fetch supported pairs for.
    pub account_id: String,
    /// Page size for pagination.
    pub page_size: Option<u8>,
    /// Page cursor for pagination.
    pub page_cursor: Option<String>,
}

/// struct for passing parameters to the method
/// [`ConnectedAccountsBetaApi::get_connected_accounts`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct GetConnectedAccountsParams {
    /// Whether to include only main accounts in the response.
    pub main_accounts: Option<bool>,
    /// Page size for pagination.
    pub page_size: Option<u8>,
    /// Page cursor for pagination.
    pub page_cursor: Option<String>,
}

#[async_trait]
impl ConnectedAccountsBetaApi for ConnectedAccountsBetaApiClient {
    /// Retrieve detailed information about a specific connected account by ID.
    /// **Note:** This endpoint is currently in beta and might be subject to
    /// changes.
    async fn get_connected_account(
        &self,
        params: GetConnectedAccountParams,
    ) -> Result<models::ConnectedSingleAccountResponse, Error<GetConnectedAccountError>> {
        let GetConnectedAccountParams { account_id } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/connected_accounts/{accountId}",
            local_var_configuration.base_path,
            accountId = crate::apis::urlencode(account_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => {
                    crate::deserialize_wrapper(&local_var_content).map_err(Error::from)
                }
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to \
                         `models::ConnectedSingleAccountResponse`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be \
                         converted to `models::ConnectedSingleAccountResponse`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<GetConnectedAccountError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieve current asset balances for a specific connected account as a
    /// flat list (one row per `assetId`, `balanceType`).  **Note:** This
    /// endpoint is currently in beta and might be subject to changes.
    async fn get_connected_account_balances(
        &self,
        params: GetConnectedAccountBalancesParams,
    ) -> Result<models::ConnectedAccountBalancesResponse, Error<GetConnectedAccountBalancesError>>
    {
        let GetConnectedAccountBalancesParams {
            account_id,
            page_size,
            page_cursor,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/connected_accounts/{accountId}/balances",
            local_var_configuration.base_path,
            accountId = crate::apis::urlencode(account_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = page_size {
            local_var_req_builder =
                local_var_req_builder.query(&[("pageSize", &param_value.to_string())]);
        }
        if let Some(ref param_value) = page_cursor {
            local_var_req_builder =
                local_var_req_builder.query(&[("pageCursor", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => {
                    crate::deserialize_wrapper(&local_var_content).map_err(Error::from)
                }
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to \
                         `models::ConnectedAccountBalancesResponse`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be \
                         converted to `models::ConnectedAccountBalancesResponse`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<GetConnectedAccountBalancesError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieve current exchange rates for converting between specific assets
    /// in a connected account.  **Note:** This endpoint is currently in beta
    /// and might be subject to changes.
    async fn get_connected_account_rates(
        &self,
        params: GetConnectedAccountRatesParams,
    ) -> Result<models::ConnectedAccountRateResponse, Error<GetConnectedAccountRatesError>> {
        let GetConnectedAccountRatesParams {
            account_id,
            base_asset_id,
            quote_asset_id,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/connected_accounts/{accountId}/rates",
            local_var_configuration.base_path,
            accountId = crate::apis::urlencode(account_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder =
            local_var_req_builder.query(&[("baseAssetId", &base_asset_id.to_string())]);
        local_var_req_builder =
            local_var_req_builder.query(&[("quoteAssetId", &quote_asset_id.to_string())]);
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => {
                    crate::deserialize_wrapper(&local_var_content).map_err(Error::from)
                }
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to \
                         `models::ConnectedAccountRateResponse`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be \
                         converted to `models::ConnectedAccountRateResponse`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<GetConnectedAccountRatesError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieve all asset trading pairs supported by a specific connected
    /// account, including the pair type (`quote`, `market`, `onOffRamp`).
    /// **Note:** This endpoint is currently in beta and might be subject to
    /// changes.
    async fn get_connected_account_trading_pairs(
        &self,
        params: GetConnectedAccountTradingPairsParams,
    ) -> Result<
        models::ConnectedAccountTradingPairsResponse,
        Error<GetConnectedAccountTradingPairsError>,
    > {
        let GetConnectedAccountTradingPairsParams {
            account_id,
            page_size,
            page_cursor,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/connected_accounts/{accountId}/manifest/capabilities/trading/pairs",
            local_var_configuration.base_path,
            accountId = crate::apis::urlencode(account_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = page_size {
            local_var_req_builder =
                local_var_req_builder.query(&[("pageSize", &param_value.to_string())]);
        }
        if let Some(ref param_value) = page_cursor {
            local_var_req_builder =
                local_var_req_builder.query(&[("pageCursor", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => {
                    crate::deserialize_wrapper(&local_var_content).map_err(Error::from)
                }
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to \
                         `models::ConnectedAccountTradingPairsResponse`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be \
                         converted to `models::ConnectedAccountTradingPairsResponse`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<GetConnectedAccountTradingPairsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Returns all connected accounts.  **Note:** This endpoint is currently in
    /// beta and might be subject to changes.
    async fn get_connected_accounts(
        &self,
        params: GetConnectedAccountsParams,
    ) -> Result<models::ConnectedAccountsResponse, Error<GetConnectedAccountsError>> {
        let GetConnectedAccountsParams {
            main_accounts,
            page_size,
            page_cursor,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/connected_accounts", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = main_accounts {
            local_var_req_builder =
                local_var_req_builder.query(&[("mainAccounts", &param_value.to_string())]);
        }
        if let Some(ref param_value) = page_size {
            local_var_req_builder =
                local_var_req_builder.query(&[("pageSize", &param_value.to_string())]);
        }
        if let Some(ref param_value) = page_cursor {
            local_var_req_builder =
                local_var_req_builder.query(&[("pageCursor", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => {
                    crate::deserialize_wrapper(&local_var_content).map_err(Error::from)
                }
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to \
                         `models::ConnectedAccountsResponse`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be \
                         converted to `models::ConnectedAccountsResponse`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<GetConnectedAccountsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method
/// [`ConnectedAccountsBetaApi::get_connected_account`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetConnectedAccountError {
    DefaultResponse(models::ErrorSchema),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method
/// [`ConnectedAccountsBetaApi::get_connected_account_balances`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetConnectedAccountBalancesError {
    DefaultResponse(models::ErrorSchema),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method
/// [`ConnectedAccountsBetaApi::get_connected_account_rates`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetConnectedAccountRatesError {
    DefaultResponse(models::ErrorSchema),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method
/// [`ConnectedAccountsBetaApi::get_connected_account_trading_pairs`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetConnectedAccountTradingPairsError {
    DefaultResponse(models::ErrorSchema),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method
/// [`ConnectedAccountsBetaApi::get_connected_accounts`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetConnectedAccountsError {
    DefaultResponse(models::ErrorSchema),
    UnknownValue(serde_json::Value),
}
