// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    super::{Error, configuration},
    crate::{
        apis::{ContentType, ResponseContent},
        models,
    },
    async_trait::async_trait,
    reqwest,
    serde::{Deserialize, Serialize, de::Error as _},
    std::sync::Arc,
};

#[async_trait]
pub trait PolicyEditorV2BetaApi: Send + Sync {
    /// GET /policy/active_policy
    ///
    /// **Note:** This endpoint is currently in beta and subject to change. If
    /// you want to participate in the Policies beta, contact your Fireblocks
    /// Customer Success Manager or send an email to csm@fireblocks.com.
    /// Returns the active policy and its validation for a specific policy type.
    /// **Endpoint Permissions:** Owner, Admin, Non-Signing Admin.
    async fn get_active_v2_policy(
        &self,
        params: GetActiveV2PolicyParams,
    ) -> Result<models::PolicyAndValidationResponseV2, Error<GetActiveV2PolicyError>>;

    /// GET /policy/draft
    ///
    /// **Note:** This endpoint is currently in beta and subject to change. If
    /// you want to participate in the Policies beta, contact your Fireblocks
    /// Customer Success Manager or send an email to csm@fireblocks.com.
    /// Returns the active draft and its validation for a specific policy type.
    /// **Endpoint Permissions:** Owner, Admin, Non-Signing Admin.
    async fn get_v2_draft(
        &self,
        params: GetV2DraftParams,
    ) -> Result<models::DraftReviewAndValidationResponseV2, Error<GetV2DraftError>>;

    /// POST /policy/draft
    ///
    /// **Note:** This endpoint is currently in beta and subject to change. If
    /// you want to participate in the Policies beta, contact your Fireblocks
    /// Customer Success Manager or send an email to csm@fireblocks.com.
    /// Publishes a draft policy by request, and returns the response.
    /// **Endpoint Permissions:** Owner, Admin, Non-Signing Admin.
    async fn publish_v2_draft(
        &self,
        params: PublishV2DraftParams,
    ) -> Result<models::PublishResultV2, Error<PublishV2DraftError>>;

    /// PUT /policy/draft
    ///
    /// **Note:** This endpoint is currently in beta and subject to change. If
    /// you want to participate in the Policies beta, contact your Fireblocks
    /// Customer Success Manager or send an email to csm@fireblocks.com.
    /// Updates the draft and returns its validation for specific policy types.
    /// **Endpoint Permissions:** Owner, Admin, Non-Signing Admin.
    async fn update_v2_draft(
        &self,
        params: UpdateV2DraftParams,
    ) -> Result<models::DraftReviewAndValidationResponseV2, Error<UpdateV2DraftError>>;
}

pub struct PolicyEditorV2BetaApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl PolicyEditorV2BetaApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

/// struct for passing parameters to the method
/// [`PolicyEditorV2BetaApi::get_active_v2_policy`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct GetActiveV2PolicyParams {
    /// The policy type(s) to retrieve. Can be a single type or multiple types
    /// by repeating the parameter (e.g., ?policyType=TRANSFER&policyType=MINT).
    pub policy_type: models::PolicyTypeV2,
}

/// struct for passing parameters to the method
/// [`PolicyEditorV2BetaApi::get_v2_draft`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct GetV2DraftParams {
    /// The policy type(s) to retrieve. Can be a single type or multiple types
    /// by repeating the parameter (e.g., ?policyType=TRANSFER&policyType=MINT).
    pub policy_type: models::PolicyTypeV2,
}

/// struct for passing parameters to the method
/// [`PolicyEditorV2BetaApi::publish_v2_draft`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct PublishV2DraftParams {
    pub publish_draft_request_v2: models::PublishDraftRequestV2,
    /// A unique identifier for the request. If the request is sent multiple
    /// times with the same idempotency key, the server will return the same
    /// response as the first request. The idempotency key is valid for 24
    /// hours.
    pub idempotency_key: Option<String>,
}

/// struct for passing parameters to the method
/// [`PolicyEditorV2BetaApi::update_v2_draft`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct UpdateV2DraftParams {
    pub update_draft_request_v2: models::UpdateDraftRequestV2,
    /// A unique identifier for the request. If the request is sent multiple
    /// times with the same idempotency key, the server will return the same
    /// response as the first request. The idempotency key is valid for 24
    /// hours.
    pub idempotency_key: Option<String>,
}

#[async_trait]
impl PolicyEditorV2BetaApi for PolicyEditorV2BetaApiClient {
    /// **Note:** This endpoint is currently in beta and subject to change. If
    /// you want to participate in the Policies beta, contact your Fireblocks
    /// Customer Success Manager or send an email to csm@fireblocks.com.
    /// Returns the active policy and its validation for a specific policy type.
    /// **Endpoint Permissions:** Owner, Admin, Non-Signing Admin.
    async fn get_active_v2_policy(
        &self,
        params: GetActiveV2PolicyParams,
    ) -> Result<models::PolicyAndValidationResponseV2, Error<GetActiveV2PolicyError>> {
        let GetActiveV2PolicyParams { policy_type } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str =
            format!("{}/policy/active_policy", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder =
            local_var_req_builder.query(&[("policyType", &policy_type.to_string())]);
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => {
                    crate::deserialize_wrapper(&local_var_content).map_err(Error::from)
                }
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to \
                         `models::PolicyAndValidationResponseV2`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be \
                         converted to `models::PolicyAndValidationResponseV2`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<GetActiveV2PolicyError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// **Note:** This endpoint is currently in beta and subject to change. If
    /// you want to participate in the Policies beta, contact your Fireblocks
    /// Customer Success Manager or send an email to csm@fireblocks.com.
    /// Returns the active draft and its validation for a specific policy type.
    /// **Endpoint Permissions:** Owner, Admin, Non-Signing Admin.
    async fn get_v2_draft(
        &self,
        params: GetV2DraftParams,
    ) -> Result<models::DraftReviewAndValidationResponseV2, Error<GetV2DraftError>> {
        let GetV2DraftParams { policy_type } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/policy/draft", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder =
            local_var_req_builder.query(&[("policyType", &policy_type.to_string())]);
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => {
                    crate::deserialize_wrapper(&local_var_content).map_err(Error::from)
                }
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to \
                         `models::DraftReviewAndValidationResponseV2`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be \
                         converted to `models::DraftReviewAndValidationResponseV2`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<GetV2DraftError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// **Note:** This endpoint is currently in beta and subject to change. If
    /// you want to participate in the Policies beta, contact your Fireblocks
    /// Customer Success Manager or send an email to csm@fireblocks.com.
    /// Publishes a draft policy by request, and returns the response.
    /// **Endpoint Permissions:** Owner, Admin, Non-Signing Admin.
    async fn publish_v2_draft(
        &self,
        params: PublishV2DraftParams,
    ) -> Result<models::PublishResultV2, Error<PublishV2DraftError>> {
        let PublishV2DraftParams {
            publish_draft_request_v2,
            idempotency_key,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/policy/draft", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = idempotency_key {
            local_var_req_builder =
                local_var_req_builder.header("Idempotency-Key", local_var_param_value.to_string());
        }
        local_var_req_builder = local_var_req_builder.json(&publish_draft_request_v2);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => {
                    crate::deserialize_wrapper(&local_var_content).map_err(Error::from)
                }
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to \
                         `models::PublishResultV2`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be \
                         converted to `models::PublishResultV2`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<PublishV2DraftError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// **Note:** This endpoint is currently in beta and subject to change. If
    /// you want to participate in the Policies beta, contact your Fireblocks
    /// Customer Success Manager or send an email to csm@fireblocks.com.
    /// Updates the draft and returns its validation for specific policy types.
    /// **Endpoint Permissions:** Owner, Admin, Non-Signing Admin.
    async fn update_v2_draft(
        &self,
        params: UpdateV2DraftParams,
    ) -> Result<models::DraftReviewAndValidationResponseV2, Error<UpdateV2DraftError>> {
        let UpdateV2DraftParams {
            update_draft_request_v2,
            idempotency_key,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/policy/draft", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = idempotency_key {
            local_var_req_builder =
                local_var_req_builder.header("Idempotency-Key", local_var_param_value.to_string());
        }
        local_var_req_builder = local_var_req_builder.json(&update_draft_request_v2);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => {
                    crate::deserialize_wrapper(&local_var_content).map_err(Error::from)
                }
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to \
                         `models::DraftReviewAndValidationResponseV2`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be \
                         converted to `models::DraftReviewAndValidationResponseV2`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<UpdateV2DraftError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method
/// [`PolicyEditorV2BetaApi::get_active_v2_policy`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetActiveV2PolicyError {
    DefaultResponse(models::ErrorSchema),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`PolicyEditorV2BetaApi::get_v2_draft`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetV2DraftError {
    DefaultResponse(models::ErrorSchema),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method
/// [`PolicyEditorV2BetaApi::publish_v2_draft`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PublishV2DraftError {
    DefaultResponse(models::ErrorSchema),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`PolicyEditorV2BetaApi::update_v2_draft`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateV2DraftError {
    DefaultResponse(models::ErrorSchema),
    UnknownValue(serde_json::Value),
}
