// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// AccountIdentifierV2 : Account identifier with type, ID, subtype, and address
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountIdentifierV2 {
    #[serde(rename = "type")]
    pub r#type: models::AccountTypeV2,
    /// Account ID
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Account subtype
    #[serde(rename = "subType", skip_serializing_if = "Option::is_none")]
    pub sub_type: Option<String>,
    /// Account address
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
}

impl AccountIdentifierV2 {
    /// Account identifier with type, ID, subtype, and address
    pub fn new(r#type: models::AccountTypeV2) -> AccountIdentifierV2 {
        AccountIdentifierV2 {
            r#type,
            id: None,
            sub_type: None,
            address: None,
        }
    }
}
