// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountHolderDetails {
    /// Full name of the account holder.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "city", skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    /// Country code, as specified in ISO 3166-1 alpha-2.
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// Country administrative subdivision, as specified in ISO 3166-2.
    #[serde(rename = "subdivision", skip_serializing_if = "Option::is_none")]
    pub subdivision: Option<String>,
    /// Account holder street address.
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "postalCode", skip_serializing_if = "Option::is_none")]
    pub postal_code: Option<String>,
}

impl AccountHolderDetails {
    pub fn new(name: String) -> AccountHolderDetails {
        AccountHolderDetails {
            name,
            city: None,
            country: None,
            subdivision: None,
            address: None,
            postal_code: None,
        }
    }
}
