// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountAccess {
    /// Indicates this uses account-based access
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The ID of the provider
    #[serde(rename = "providerId", skip_serializing_if = "Option::is_none")]
    pub provider_id: Option<String>,
    /// The ID of the account
    #[serde(rename = "accountId")]
    pub account_id: String,
}

impl AccountAccess {
    pub fn new(r#type: Type, account_id: String) -> AccountAccess {
        AccountAccess {
            r#type,
            provider_id: None,
            account_id,
        }
    }
}
/// Indicates this uses account-based access
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "PROVIDER_ACCOUNT")]
    ProviderAccount,
}

impl Default for Type {
    fn default() -> Type {
        Self::ProviderAccount
    }
}
