// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountBasedAccessProvider {
    /// Unique identifier for the provider
    #[serde(rename = "id")]
    pub id: String,
    /// Display name of the provider
    #[serde(rename = "name")]
    pub name: String,
    /// URL to the logo image of the provider
    #[serde(rename = "logo", skip_serializing_if = "Option::is_none")]
    pub logo: Option<String>,
    /// Indicates whether the provider access model is through accounts or
    /// directly
    #[serde(rename = "accountBased")]
    pub account_based: bool,
    #[serde(rename = "manifest")]
    pub manifest: models::Manifest,
    /// Whether the provider is currently connected
    #[serde(rename = "connected")]
    pub connected: bool,
    #[serde(rename = "accounts", skip_serializing_if = "Option::is_none")]
    pub accounts: Option<Vec<models::AccountBase>>,
}

impl AccountBasedAccessProvider {
    pub fn new(
        id: String,
        name: String,
        account_based: bool,
        manifest: models::Manifest,
        connected: bool,
    ) -> AccountBasedAccessProvider {
        AccountBasedAccessProvider {
            id,
            name,
            logo: None,
            account_based,
            manifest,
            connected,
            accounts: None,
        }
    }
}
