// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// AccountTypeV2 : Type of account
/// Type of account
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccountTypeV2 {
    #[serde(rename = "EXCHANGE")]
    Exchange,
    #[serde(rename = "UNMANAGED")]
    Unmanaged,
    #[serde(rename = "VAULT")]
    Vault,
    #[serde(rename = "GLOBAL_WHITELIST")]
    GlobalWhitelist,
    #[serde(rename = "NETWORK_CONNECTION")]
    NetworkConnection,
    #[serde(rename = "FIAT_ACCOUNT")]
    FiatAccount,
    #[serde(rename = "CONNECTED_ACCOUNT")]
    ConnectedAccount,
    #[serde(rename = "ONE_TIME_ADDRESS")]
    OneTimeAddress,
    #[serde(rename = "SRC_DST_NA")]
    SrcDstNa,
    #[serde(rename = "MULTIPLE_VENUES")]
    MultipleVenues,
    #[serde(rename = "END_USER_WALLET")]
    EndUserWallet,
    #[serde(rename = "OEC_PARTNER")]
    OecPartner,
    #[serde(rename = "CONTRACT")]
    Contract,
    #[serde(rename = "INTERNAL")]
    Internal,
    #[serde(rename = "EXTERNAL")]
    External,
    #[serde(rename = "DAPP_CONNECTION")]
    DappConnection,
    #[serde(rename = "UNKNOWN")]
    Unknown,
    #[serde(rename = "*")]
    Star,
    #[serde(rename = "ANY")]
    Any,
}

impl std::fmt::Display for AccountTypeV2 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Exchange => write!(f, "EXCHANGE"),
            Self::Unmanaged => write!(f, "UNMANAGED"),
            Self::Vault => write!(f, "VAULT"),
            Self::GlobalWhitelist => write!(f, "GLOBAL_WHITELIST"),
            Self::NetworkConnection => write!(f, "NETWORK_CONNECTION"),
            Self::FiatAccount => write!(f, "FIAT_ACCOUNT"),
            Self::ConnectedAccount => write!(f, "CONNECTED_ACCOUNT"),
            Self::OneTimeAddress => write!(f, "ONE_TIME_ADDRESS"),
            Self::SrcDstNa => write!(f, "SRC_DST_NA"),
            Self::MultipleVenues => write!(f, "MULTIPLE_VENUES"),
            Self::EndUserWallet => write!(f, "END_USER_WALLET"),
            Self::OecPartner => write!(f, "OEC_PARTNER"),
            Self::Contract => write!(f, "CONTRACT"),
            Self::Internal => write!(f, "INTERNAL"),
            Self::External => write!(f, "EXTERNAL"),
            Self::DappConnection => write!(f, "DAPP_CONNECTION"),
            Self::Unknown => write!(f, "UNKNOWN"),
            Self::Star => write!(f, "*"),
            Self::Any => write!(f, "ANY"),
        }
    }
}

impl Default for AccountTypeV2 {
    fn default() -> AccountTypeV2 {
        Self::Exchange
    }
}
