// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountProviderId {
    /// The ID of the provider associated with the account.
    #[serde(rename = "providerId")]
    pub provider_id: String,
    /// The ID of the account associated with the provider.
    #[serde(rename = "accountId")]
    pub account_id: String,
}

impl AccountProviderId {
    pub fn new(provider_id: String, account_id: String) -> AccountProviderId {
        AccountProviderId {
            provider_id,
            account_id,
        }
    }
}
