// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// AccountConfigV2 : Policy source/destination configuration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountConfigV2 {
    #[serde(rename = "type")]
    pub r#type: models::AccountTypeV2,
    #[serde(rename = "subType", skip_serializing_if = "Option::is_none")]
    pub sub_type: Option<Vec<models::AccountIdentifierV2>>,
    #[serde(rename = "ids", skip_serializing_if = "Option::is_none")]
    pub ids: Option<Vec<models::AccountIdentifierV2>>,
    #[serde(rename = "operator")]
    pub operator: models::PolicyOperatorV2,
    /// Whether to match from account or source
    #[serde(rename = "matchFrom", skip_serializing_if = "Option::is_none")]
    pub match_from: Option<MatchFrom>,
}

impl AccountConfigV2 {
    /// Policy source/destination configuration
    pub fn new(
        r#type: models::AccountTypeV2,
        operator: models::PolicyOperatorV2,
    ) -> AccountConfigV2 {
        AccountConfigV2 {
            r#type,
            sub_type: None,
            ids: None,
            operator,
            match_from: None,
        }
    }
}
/// Whether to match from account or source
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MatchFrom {
    #[serde(rename = "ACCOUNT")]
    Account,
    #[serde(rename = "SOURCE")]
    Source,
}

impl Default for MatchFrom {
    fn default() -> MatchFrom {
        Self::Account
    }
}
