// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AchAddress {
    #[serde(rename = "accountHolder")]
    pub account_holder: models::AccountHolderDetails,
    /// Name of the bank.
    #[serde(rename = "bankName", skip_serializing_if = "Option::is_none")]
    pub bank_name: Option<String>,
    /// The bank account number for the ACH transfer.
    #[serde(rename = "bankAccountNumber")]
    pub bank_account_number: String,
    /// Routing number identifying the bank account.
    #[serde(rename = "routingNumber")]
    pub routing_number: String,
    #[serde(rename = "accountType")]
    pub account_type: models::AchAccountType,
}

impl AchAddress {
    pub fn new(
        account_holder: models::AccountHolderDetails,
        bank_account_number: String,
        routing_number: String,
        account_type: models::AchAccountType,
    ) -> AchAddress {
        AchAddress {
            account_holder,
            bank_name: None,
            bank_account_number,
            routing_number,
            account_type,
        }
    }
}
