// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// AchAccountType : Type of the bank account.
/// Type of the bank account.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AchAccountType {
    #[serde(rename = "CHECKING")]
    Checking,
    #[serde(rename = "SAVINGS")]
    Savings,
}

impl std::fmt::Display for AchAccountType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Checking => write!(f, "CHECKING"),
            Self::Savings => write!(f, "SAVINGS"),
        }
    }
}

impl Default for AchAccountType {
    fn default() -> AchAccountType {
        Self::Checking
    }
}
