// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// AdditionalInfoRequestAdditionalInfo : Additional payment information based
/// on the payment rail type Additional payment information based on the payment
/// rail type
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AdditionalInfoRequestAdditionalInfo {
    IbanPaymentInfo(models::IbanPaymentInfo),
    AbaPaymentInfo(models::AbaPaymentInfo),
    SpeiBasicPaymentInfo(models::SpeiBasicPaymentInfo),
    SpeiAdvancedPaymentInfo(models::SpeiAdvancedPaymentInfo),
    PixPaymentInfo(models::PixPaymentInfo),
    SepaPaymentInfo(models::SepaPaymentInfo),
    AchPaymentInfo(models::AchPaymentInfo),
    UsWirePaymentInfo(models::UsWirePaymentInfo),
    MomoPaymentInfo(models::MomoPaymentInfo),
    LbtPaymentInfo(models::LbtPaymentInfo),
}

impl Default for AdditionalInfoRequestAdditionalInfo {
    fn default() -> Self {
        Self::IbanPaymentInfo(Default::default())
    }
}
/// The payment rail type for Lebanese bank transfers
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Rail {
    #[serde(rename = "LBT")]
    Lbt,
}

impl Default for Rail {
    fn default() -> Rail {
        Self::Lbt
    }
}
/// The addressing system used for Lebanese bank transfers (Bank Account Number)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AddressingSystem {
    #[serde(rename = "BAN")]
    Ban,
}

impl Default for AddressingSystem {
    fn default() -> AddressingSystem {
        Self::Ban
    }
}
/// The type of PIX key being used
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum KeyType {
    #[serde(rename = "CPF")]
    Cpf,
    #[serde(rename = "CNPJ")]
    Cnpj,
    #[serde(rename = "EMAIL")]
    Email,
    #[serde(rename = "PHONE")]
    Phone,
    #[serde(rename = "RANDOM")]
    Random,
}

impl Default for KeyType {
    fn default() -> KeyType {
        Self::Cpf
    }
}
/// The type of bank account
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccountType {
    #[serde(rename = "CHECKING")]
    Checking,
    #[serde(rename = "SAVINGS")]
    Savings,
}

impl Default for AccountType {
    fn default() -> AccountType {
        Self::Checking
    }
}
/// The mobile money service provider
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Provider {
    #[serde(rename = "M_PESA")]
    MPesa,
    #[serde(rename = "AIRTEL")]
    Airtel,
    #[serde(rename = "MTN")]
    Mtn,
    #[serde(rename = "TIGO")]
    Tigo,
}

impl Default for Provider {
    fn default() -> Provider {
        Self::MPesa
    }
}
