// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// AdditionalInfoRequest : External wallet request with additional payment
/// information for various payment rails
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdditionalInfoRequest {
    #[serde(rename = "additionalInfo")]
    pub additional_info: models::AdditionalInfoRequestAdditionalInfo,
}

impl AdditionalInfoRequest {
    /// External wallet request with additional payment information for various
    /// payment rails
    pub fn new(
        additional_info: models::AdditionalInfoRequestAdditionalInfo,
    ) -> AdditionalInfoRequest {
        AdditionalInfoRequest { additional_info }
    }
}
