// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AmlVerdictManualRequest {
    /// The AML verdict to set for the transaction.
    #[serde(rename = "verdict")]
    pub verdict: Verdict,
    /// The transaction ID to set the verdict for.
    #[serde(rename = "txId")]
    pub tx_id: uuid::Uuid,
}

impl AmlVerdictManualRequest {
    pub fn new(verdict: Verdict, tx_id: uuid::Uuid) -> AmlVerdictManualRequest {
        AmlVerdictManualRequest { verdict, tx_id }
    }
}
/// The AML verdict to set for the transaction.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Verdict {
    #[serde(rename = "ACCEPT")]
    Accept,
    #[serde(rename = "REJECT")]
    Reject,
}

impl Default for Verdict {
    fn default() -> Verdict {
        Self::Accept
    }
}
