// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// AmountRangeV2 : Amount range configuration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AmountRangeV2 {
    /// Minimum amount
    #[serde(rename = "min")]
    pub min: String,
    /// Maximum amount
    #[serde(rename = "max")]
    pub max: String,
    /// Currency for the amount
    #[serde(rename = "currency")]
    pub currency: String,
}

impl AmountRangeV2 {
    /// Amount range configuration
    pub fn new(min: String, max: String, currency: String) -> AmountRangeV2 {
        AmountRangeV2 { min, max, currency }
    }
}
