// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// AmountOverTimeConfigV2Range : Amount range configuration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AmountOverTimeConfigV2Range {
    /// Minimum amount
    #[serde(rename = "min")]
    pub min: String,
    /// Maximum amount (optional)
    #[serde(rename = "max", skip_serializing_if = "Option::is_none")]
    pub max: Option<String>,
}

impl AmountOverTimeConfigV2Range {
    /// Amount range configuration
    pub fn new(min: String) -> AmountOverTimeConfigV2Range {
        AmountOverTimeConfigV2Range { min, max: None }
    }
}
