// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApproversConfigV2ApprovalGroupsInner {
    /// Approval threshold
    #[serde(rename = "threshold")]
    pub threshold: f64,
    /// List of user IDs
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<String>>,
    /// List of policy group IDs
    #[serde(rename = "groups", skip_serializing_if = "Option::is_none")]
    pub groups: Option<Vec<String>>,
}

impl ApproversConfigV2ApprovalGroupsInner {
    pub fn new(threshold: f64) -> ApproversConfigV2ApprovalGroupsInner {
        ApproversConfigV2ApprovalGroupsInner {
            threshold,
            users: None,
            groups: None,
        }
    }
}
