// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// ApproversConfigV2 : Approvers configuration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApproversConfigV2 {
    /// Whether initiator can approve
    #[serde(
        rename = "canInitiatorApprove",
        skip_serializing_if = "Option::is_none"
    )]
    pub can_initiator_approve: Option<bool>,
    /// Operator for approval groups
    #[serde(rename = "operator", skip_serializing_if = "Option::is_none")]
    pub operator: Option<Operator>,
    /// Whether operator can be authorizer
    #[serde(
        rename = "allowOperatorAsAuthorizer",
        skip_serializing_if = "Option::is_none"
    )]
    pub allow_operator_as_authorizer: Option<bool>,
    /// List of approval groups
    #[serde(rename = "approvalGroups", skip_serializing_if = "Option::is_none")]
    pub approval_groups: Option<Vec<models::ApproversConfigV2ApprovalGroupsInner>>,
}

impl ApproversConfigV2 {
    /// Approvers configuration
    pub fn new() -> ApproversConfigV2 {
        ApproversConfigV2 {
            can_initiator_approve: None,
            operator: None,
            allow_operator_as_authorizer: None,
            approval_groups: None,
        }
    }
}
/// Operator for approval groups
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Operator {
    #[serde(rename = "AND")]
    And,
    #[serde(rename = "OR")]
    Or,
}

impl Default for Operator {
    fn default() -> Operator {
        Self::And
    }
}
