// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// ApprovalRequest : Approval request details
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApprovalRequest {
    /// The approval request identifier
    #[serde(rename = "id")]
    pub id: String,
    /// The approval request type
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The approval request state
    #[serde(rename = "state")]
    pub state: State,
}

impl ApprovalRequest {
    /// Approval request details
    pub fn new(id: String, r#type: Type, state: State) -> ApprovalRequest {
        ApprovalRequest { id, r#type, state }
    }
}
/// The approval request type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "TAG_UPDATE")]
    TagUpdate,
    #[serde(rename = "TAG_DELETE")]
    TagDelete,
    #[serde(rename = "TAG_ATTACH_DETACH")]
    TagAttachDetach,
}

impl Default for Type {
    fn default() -> Type {
        Self::TagUpdate
    }
}
/// The approval request state
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "PENDING")]
    Pending,
    #[serde(rename = "APPROVED")]
    Approved,
    #[serde(rename = "REJECTED")]
    Rejected,
    #[serde(rename = "FAILED")]
    Failed,
    #[serde(rename = "CANCELLED")]
    Cancelled,
    #[serde(rename = "EXPIRED")]
    Expired,
}

impl Default for State {
    fn default() -> State {
        Self::Pending
    }
}
