// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// AssetFeature : Asset feature
/// Asset feature
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AssetFeature {
    #[serde(rename = "STABLECOIN")]
    Stablecoin,
}

impl std::fmt::Display for AssetFeature {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Stablecoin => write!(f, "STABLECOIN"),
        }
    }
}

impl Default for AssetFeature {
    fn default() -> AssetFeature {
        Self::Stablecoin
    }
}
