// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetDetailsMetadata {
    #[serde(rename = "scope")]
    pub scope: models::AssetScope,
    /// Is asset deprecated
    #[serde(rename = "deprecated")]
    pub deprecated: bool,
    /// New asset ID replacement
    #[serde(
        rename = "deprecationReferralId",
        skip_serializing_if = "Option::is_none"
    )]
    pub deprecation_referral_id: Option<String>,
    /// Is asset verified by Fireblocks
    #[serde(rename = "verified")]
    pub verified: bool,
    /// Vendor’s website
    #[serde(rename = "website", skip_serializing_if = "Option::is_none")]
    pub website: Option<String>,
    /// Asset’s media
    #[serde(rename = "media", skip_serializing_if = "Option::is_none")]
    pub media: Option<Vec<models::Media>>,
    #[serde(rename = "note", skip_serializing_if = "Option::is_none")]
    pub note: Option<models::AssetNote>,
    /// Asset features
    #[serde(rename = "features", skip_serializing_if = "Option::is_none")]
    pub features: Option<Vec<models::AssetFeature>>,
}

impl AssetDetailsMetadata {
    pub fn new(
        scope: models::AssetScope,
        deprecated: bool,
        verified: bool,
    ) -> AssetDetailsMetadata {
        AssetDetailsMetadata {
            scope,
            deprecated,
            deprecation_referral_id: None,
            verified,
            website: None,
            media: None,
            note: None,
            features: None,
        }
    }
}
