// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetNote {
    /// Note content
    #[serde(rename = "text")]
    pub text: String,
    /// Who updated the note (UUID)
    #[serde(rename = "userId")]
    pub user_id: uuid::Uuid,
    /// User name
    #[serde(rename = "userName")]
    pub user_name: String,
    /// ISO Timestamp when last updated
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl AssetNote {
    pub fn new(
        text: String,
        user_id: uuid::Uuid,
        user_name: String,
        updated_at: String,
    ) -> AssetNote {
        AssetNote {
            text,
            user_id,
            user_name,
            updated_at,
        }
    }
}
