// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// AssetConfigV2 : Policy asset configuration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetConfigV2 {
    /// Whether this is an NFT transfer
    #[serde(rename = "nftTransfer")]
    pub nft_transfer: bool,
    /// List of asset types
    #[serde(rename = "assetTypes", skip_serializing_if = "Option::is_none")]
    pub asset_types: Option<Vec<models::AssetTypesConfigV2Inner>>,
    #[serde(rename = "operator", skip_serializing_if = "Option::is_none")]
    pub operator: Option<models::PolicyOperatorV2>,
}

impl AssetConfigV2 {
    /// Policy asset configuration
    pub fn new(nft_transfer: bool) -> AssetConfigV2 {
        AssetConfigV2 {
            nft_transfer,
            asset_types: None,
            operator: None,
        }
    }
}
