// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// BasicAddressRequest : Basic external wallet request with address information
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BasicAddressRequest {
    /// The external wallet's address (or its xpub)
    #[serde(rename = "address")]
    pub address: String,
    /// - For XRP wallets, the destination tag. - For EOS/XLM wallets, the memo.
    ///   - For fiat providers, the Bank Transfer Description.
    #[serde(rename = "tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
}

impl BasicAddressRequest {
    /// Basic external wallet request with address information
    pub fn new(address: String) -> BasicAddressRequest {
        BasicAddressRequest { address, tag: None }
    }
}
