// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BpsFee {
    #[serde(rename = "amountType")]
    pub amount_type: AmountType,
    /// Fee in basis points (1 = 0.01%, 10000 = 100%)
    #[serde(rename = "amount")]
    pub amount: f64,
}

impl BpsFee {
    pub fn new(amount_type: AmountType, amount: f64) -> BpsFee {
        BpsFee {
            amount_type,
            amount,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AmountType {
    #[serde(rename = "BPS")]
    Bps,
}

impl Default for AmountType {
    fn default() -> AmountType {
        Self::Bps
    }
}
