// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BusinessIdentification {
    #[serde(rename = "externalReferenceId")]
    pub external_reference_id: String,
    #[serde(rename = "entityType")]
    pub entity_type: EntityType,
    #[serde(rename = "participantRelationshipType")]
    pub participant_relationship_type: models::ParticipantRelationshipType,
    #[serde(rename = "businessName")]
    pub business_name: String,
    #[serde(rename = "registrationNumber")]
    pub registration_number: String,
    #[serde(rename = "postalAddress")]
    pub postal_address: models::PostalAddress,
}

impl BusinessIdentification {
    pub fn new(
        external_reference_id: String,
        entity_type: EntityType,
        participant_relationship_type: models::ParticipantRelationshipType,
        business_name: String,
        registration_number: String,
        postal_address: models::PostalAddress,
    ) -> BusinessIdentification {
        BusinessIdentification {
            external_reference_id,
            entity_type,
            participant_relationship_type,
            business_name,
            registration_number,
            postal_address,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EntityType {
    #[serde(rename = "BUSINESS")]
    Business,
}

impl Default for EntityType {
    fn default() -> EntityType {
        Self::Business
    }
}
