// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommittedQuoteType {
    /// Indicates this is a committed quote
    #[serde(rename = "type")]
    pub r#type: Type,
    /// ISO 8601 timestamp of the expiration time of the quote.
    #[serde(rename = "expiresAt")]
    pub expires_at: String,
}

impl CommittedQuoteType {
    pub fn new(r#type: Type, expires_at: String) -> CommittedQuoteType {
        CommittedQuoteType { r#type, expires_at }
    }
}
/// Indicates this is a committed quote
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "COMMITTED")]
    Committed,
}

impl Default for Type {
    fn default() -> Type {
        Self::Committed
    }
}
