// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConnectedAccountAssetType {
    #[serde(rename = "DIGITAL")]
    Digital,
    #[serde(rename = "FIAT")]
    Fiat,
}

impl std::fmt::Display for ConnectedAccountAssetType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Digital => write!(f, "DIGITAL"),
            Self::Fiat => write!(f, "FIAT"),
        }
    }
}

impl Default for ConnectedAccountAssetType {
    fn default() -> ConnectedAccountAssetType {
        Self::Digital
    }
}
