// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectedAccountTotalBalance {
    /// The denominated currency value of the account.
    #[serde(rename = "amount")]
    pub amount: String,
    /// The asset ID of the total balance.
    #[serde(rename = "denominatedAssetId")]
    pub denominated_asset_id: String,
    /// Indicates whether the total amount represents the complete balance of
    /// all assets in the account. When true, all asset balances have been
    /// successfully converted to the denominated currency. When false, some
    /// assets could not be included in the total due to missing exchange rates
    /// or non-convertible assets.
    #[serde(rename = "hasFullAssetCoverage")]
    pub has_full_asset_coverage: bool,
}

impl ConnectedAccountTotalBalance {
    pub fn new(
        amount: String,
        denominated_asset_id: String,
        has_full_asset_coverage: bool,
    ) -> ConnectedAccountTotalBalance {
        ConnectedAccountTotalBalance {
            amount,
            denominated_asset_id,
            has_full_asset_coverage,
        }
    }
}
