// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectedAccountManifest {
    /// Asset types supported by the connected account.
    #[serde(rename = "assetTypes")]
    pub asset_types: Vec<models::ConnectedAccountAssetType>,
    /// Features supported for the connected account. Logic:   - If account
    /// capabilities include ramp -> TRADING   - If account capabilities include
    /// transfers -> DEPOSITS   - If account capabilities include
    /// transfersBlockchain / transfersFiat / transfersPeerAccounts /
    /// transfersInternal -> WITHDRAWALS
    #[serde(rename = "capabilities")]
    pub capabilities: Vec<models::ConnectedAccountCapability>,
}

impl ConnectedAccountManifest {
    pub fn new(
        asset_types: Vec<models::ConnectedAccountAssetType>,
        capabilities: Vec<models::ConnectedAccountCapability>,
    ) -> ConnectedAccountManifest {
        ConnectedAccountManifest {
            asset_types,
            capabilities,
        }
    }
}
