// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// ConnectedAccountsErrorResponseError : Error details describing the failure.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectedAccountsErrorResponseError {
    /// High-level error category.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Human-readable error description.
    #[serde(rename = "message")]
    pub message: String,
    /// Service-specific error code for troubleshooting.
    #[serde(rename = "errorCode", skip_serializing_if = "Option::is_none")]
    pub error_code: Option<String>,
}

impl ConnectedAccountsErrorResponseError {
    /// Error details describing the failure.
    pub fn new(r#type: Type, message: String) -> ConnectedAccountsErrorResponseError {
        ConnectedAccountsErrorResponseError {
            r#type,
            message,
            error_code: None,
        }
    }
}
/// High-level error category.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "INTERNAL")]
    Internal,
    #[serde(rename = "AUTHENTICATION")]
    Authentication,
    #[serde(rename = "AUTHORIZATION")]
    Authorization,
    #[serde(rename = "VALIDATION")]
    Validation,
    #[serde(rename = "NOT_FOUND")]
    NotFound,
    #[serde(rename = "UNPROCESSABLE_ENTITY")]
    UnprocessableEntity,
    #[serde(rename = "FORBIDDEN")]
    Forbidden,
}

impl Default for Type {
    fn default() -> Type {
        Self::Internal
    }
}
