// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectedAccountTradingPair {
    /// The ID of the trading pair.
    #[serde(rename = "id")]
    pub id: String,
    /// The Symbol of the base asset.
    #[serde(rename = "baseAssetId")]
    pub base_asset_id: String,
    /// The symbol of the quote asset.
    #[serde(rename = "quoteAssetId")]
    pub quote_asset_id: String,
    #[serde(rename = "supportedTypes")]
    pub supported_types: Vec<models::ConnectedAccountTradingPairSupportedType>,
}

impl ConnectedAccountTradingPair {
    pub fn new(
        id: String,
        base_asset_id: String,
        quote_asset_id: String,
        supported_types: Vec<models::ConnectedAccountTradingPairSupportedType>,
    ) -> ConnectedAccountTradingPair {
        ConnectedAccountTradingPair {
            id,
            base_asset_id,
            quote_asset_id,
            supported_types,
        }
    }
}
