// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectedSingleAccountResponse {
    /// Unique identifier of the connected account.
    #[serde(rename = "id")]
    pub id: String,
    /// Human-readable name of the connected account.
    #[serde(rename = "name")]
    pub name: String,
    /// The ID of the venue the account belongs to.
    #[serde(rename = "providerId")]
    pub provider_id: String,
    #[serde(rename = "status")]
    pub status: models::ConnectedAccountApprovalStatus,
    #[serde(rename = "manifest")]
    pub manifest: models::ConnectedAccountManifest,
    /// The ID of the parent main account, if this is a sub account.
    #[serde(rename = "parentId", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
    /// IDs of sub-accounts associated with this connected account.
    #[serde(rename = "subAccountsIds", skip_serializing_if = "Option::is_none")]
    pub sub_accounts_ids: Option<Vec<String>>,
}

impl ConnectedSingleAccountResponse {
    pub fn new(
        id: String,
        name: String,
        provider_id: String,
        status: models::ConnectedAccountApprovalStatus,
        manifest: models::ConnectedAccountManifest,
    ) -> ConnectedSingleAccountResponse {
        ConnectedSingleAccountResponse {
            id,
            name,
            provider_id,
            status,
            manifest,
            parent_id: None,
            sub_accounts_ids: None,
        }
    }
}
