// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectedAccountBalances {
    /// Asset identifier (e.g., BTC, ETH, USDC).
    #[serde(rename = "assetId")]
    pub asset_id: String,
    /// Amount available for use.
    #[serde(rename = "availableAmount")]
    pub available_amount: String,
    /// Total amount including locked/held balances.
    #[serde(rename = "totalAmount")]
    pub total_amount: String,
    /// Amount currently locked/held.
    #[serde(rename = "lockedAmount", skip_serializing_if = "Option::is_none")]
    pub locked_amount: Option<String>,
    /// Credit line amount, if applicable (0 when not used).
    #[serde(rename = "creditAmount", skip_serializing_if = "Option::is_none")]
    pub credit_amount: Option<String>,
    /// Wallet type/category (e.g., SPOT, MARGIN, FUNDING).
    #[serde(rename = "balanceType")]
    pub balance_type: String,
    /// Display name for the balance type (at the provider)
    #[serde(rename = "balanceName", skip_serializing_if = "Option::is_none")]
    pub balance_name: Option<String>,
}

impl ConnectedAccountBalances {
    pub fn new(
        asset_id: String,
        available_amount: String,
        total_amount: String,
        balance_type: String,
    ) -> ConnectedAccountBalances {
        ConnectedAccountBalances {
            asset_id,
            available_amount,
            total_amount,
            locked_amount: None,
            credit_amount: None,
            balance_type,
            balance_name: None,
        }
    }
}
