// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ContractMethodPatternV2 {
    /// All methods allowed
    String(String),
    ContractMethodConfigV2(models::ContractMethodConfigV2),
}

impl Default for ContractMethodPatternV2 {
    fn default() -> Self {
        Self::String(Default::default())
    }
}
/// Operator for method calls
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Operator {
    #[serde(rename = "EITHER")]
    Either,
    #[serde(rename = "EXACT")]
    Exact,
}

impl Default for Operator {
    fn default() -> Operator {
        Self::Either
    }
}
