// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// ContractMethodConfigV2 : Contract method configuration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractMethodConfigV2 {
    #[serde(rename = "methodCalls")]
    pub method_calls: Vec<String>,
    /// Operator for method calls
    #[serde(rename = "operator")]
    pub operator: Operator,
    /// Payload suffix for method calls
    #[serde(rename = "payloadSuffix", skip_serializing_if = "Option::is_none")]
    pub payload_suffix: Option<String>,
}

impl ContractMethodConfigV2 {
    /// Contract method configuration
    pub fn new(method_calls: Vec<String>, operator: Operator) -> ContractMethodConfigV2 {
        ContractMethodConfigV2 {
            method_calls,
            operator,
            payload_suffix: None,
        }
    }
}
/// Operator for method calls
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Operator {
    #[serde(rename = "EITHER")]
    Either,
    #[serde(rename = "EXACT")]
    Exact,
}

impl Default for Operator {
    fn default() -> Operator {
        Self::Either
    }
}
