// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOrderRequest {
    #[serde(rename = "via")]
    pub via: models::AccessType,
    #[serde(rename = "executionRequestDetails")]
    pub execution_request_details: models::ExecutionRequestDetails,
    #[serde(rename = "settlement")]
    pub settlement: models::Settlement,
    #[serde(
        rename = "participantsIdentification",
        skip_serializing_if = "Option::is_none"
    )]
    pub participants_identification: Option<models::ParticipantsIdentification>,
    /// Internal reference ID for the customer
    #[serde(
        rename = "customerInternalReferenceId",
        skip_serializing_if = "Option::is_none"
    )]
    pub customer_internal_reference_id: Option<String>,
    /// Optional note for the order
    #[serde(rename = "note", skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
}

impl CreateOrderRequest {
    pub fn new(
        via: models::AccessType,
        execution_request_details: models::ExecutionRequestDetails,
        settlement: models::Settlement,
    ) -> CreateOrderRequest {
        CreateOrderRequest {
            via,
            execution_request_details,
            settlement,
            participants_identification: None,
            customer_internal_reference_id: None,
            note: None,
        }
    }
}
