// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateTagRequest {
    /// The tag label
    #[serde(rename = "label")]
    pub label: String,
    /// Description for the tag
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The tag color in hex format
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    /// Indication of whether the tag is protected
    #[serde(rename = "isProtected", skip_serializing_if = "Option::is_none")]
    pub is_protected: Option<bool>,
}

impl CreateTagRequest {
    pub fn new(label: String) -> CreateTagRequest {
        CreateTagRequest {
            label,
            description: None,
            color: None,
            is_protected: None,
        }
    }
}
