// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// DerivationPathConfigV2 : Derivation path configuration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DerivationPathConfigV2 {
    /// Derivation path as array of numbers
    #[serde(rename = "path")]
    pub path: Vec<f64>,
    /// Whether this is a partial path
    #[serde(rename = "partial", skip_serializing_if = "Option::is_none")]
    pub partial: Option<bool>,
}

impl DerivationPathConfigV2 {
    /// Derivation path configuration
    pub fn new(path: Vec<f64>) -> DerivationPathConfigV2 {
        DerivationPathConfigV2 {
            path,
            partial: None,
        }
    }
}
