// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// DesignatedSignersConfigV2 : Designated signers configuration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DesignatedSignersConfigV2 {
    /// Type of designated signers
    #[serde(rename = "type")]
    pub r#type: Type,
    /// List of user IDs
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<String>>,
    /// List of policy group IDs
    #[serde(rename = "groups", skip_serializing_if = "Option::is_none")]
    pub groups: Option<Vec<String>>,
}

impl DesignatedSignersConfigV2 {
    /// Designated signers configuration
    pub fn new(r#type: Type) -> DesignatedSignersConfigV2 {
        DesignatedSignersConfigV2 {
            r#type,
            users: None,
            groups: None,
        }
    }
}
/// Type of designated signers
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "SINGLE")]
    Single,
    #[serde(rename = "MULTIPLE")]
    Multiple,
    #[serde(rename = "INITIATOR")]
    Initiator,
}

impl Default for Type {
    fn default() -> Type {
        Self::Single
    }
}
