// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DirectAccess {
    /// Indicates this uses direct provider access
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The ID of the provider
    #[serde(rename = "providerId")]
    pub provider_id: String,
}

impl DirectAccess {
    pub fn new(r#type: Type, provider_id: String) -> DirectAccess {
        DirectAccess {
            r#type,
            provider_id,
        }
    }
}
/// Indicates this uses direct provider access
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "PROVIDER")]
    Provider,
}

impl Default for Type {
    fn default() -> Type {
        Self::Provider
    }
}
