// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DirectAccessProvider {
    /// Unique identifier for the provider
    #[serde(rename = "id")]
    pub id: String,
    /// Display name of the provider
    #[serde(rename = "name")]
    pub name: String,
    /// URL to the logo image of the provider
    #[serde(rename = "logo", skip_serializing_if = "Option::is_none")]
    pub logo: Option<String>,
    /// Indicates whether the provider access model is through accounts or
    /// directly
    #[serde(rename = "accountBased")]
    pub account_based: bool,
    /// Whether the provider was approved for use
    #[serde(rename = "approved", skip_serializing_if = "Option::is_none")]
    pub approved: Option<bool>,
    /// Whether the provider has terms of service
    #[serde(rename = "hasTermsOfService")]
    pub has_terms_of_service: bool,
    /// URL to the terms of service document
    #[serde(rename = "termsOfServiceUrl", skip_serializing_if = "Option::is_none")]
    pub terms_of_service_url: Option<String>,
}

impl DirectAccessProvider {
    pub fn new(
        id: String,
        name: String,
        account_based: bool,
        has_terms_of_service: bool,
    ) -> DirectAccessProvider {
        DirectAccessProvider {
            id,
            name,
            logo: None,
            account_based,
            approved: None,
            has_terms_of_service,
            terms_of_service_url: None,
        }
    }
}
