// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// DraftResponseV2 : Response object for draft operations
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DraftResponseV2 {
    /// Operation status
    #[serde(rename = "status")]
    pub status: String,
    /// Draft rules
    #[serde(rename = "rules")]
    pub rules: Vec<models::PolicyRuleV2>,
    /// Draft unique id
    #[serde(rename = "draftId")]
    pub draft_id: String,
    #[serde(rename = "metadata")]
    pub metadata: models::PolicyMetadataV2,
}

impl DraftResponseV2 {
    /// Response object for draft operations
    pub fn new(
        status: String,
        rules: Vec<models::PolicyRuleV2>,
        draft_id: String,
        metadata: models::PolicyMetadataV2,
    ) -> DraftResponseV2 {
        DraftResponseV2 {
            status,
            rules,
            draft_id,
            metadata,
        }
    }
}
