// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// DraftReviewAndValidationResponseV2 : Draft validation
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DraftReviewAndValidationResponseV2 {
    #[serde(rename = "draftResponse")]
    pub draft_response: models::DraftResponseV2,
    #[serde(rename = "validation")]
    pub validation: models::PolicyValidationV2,
}

impl DraftReviewAndValidationResponseV2 {
    /// Draft validation
    pub fn new(
        draft_response: models::DraftResponseV2,
        validation: models::PolicyValidationV2,
    ) -> DraftReviewAndValidationResponseV2 {
        DraftReviewAndValidationResponseV2 {
            draft_response,
            validation,
        }
    }
}
