// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// DvpSettlement : Source/Destination accounts for the quote (must have for
/// defi quotes)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DvpSettlement {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "sourceAccount")]
    pub source_account: models::SettlementSourceAccount,
    #[serde(rename = "destinationAccount")]
    pub destination_account: models::AccountReference,
}

impl DvpSettlement {
    /// Source/Destination accounts for the quote (must have for defi quotes)
    pub fn new(
        r#type: Type,
        source_account: models::SettlementSourceAccount,
        destination_account: models::AccountReference,
    ) -> DvpSettlement {
        DvpSettlement {
            r#type,
            source_account,
            destination_account,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "DVP")]
    Dvp,
}

impl Default for Type {
    fn default() -> Type {
        Self::Dvp
    }
}
