// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// EstimatedFeeDetails : Optional detailed fee breakdown for high/medium/low
/// estimates
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EstimatedFeeDetails {
    #[serde(rename = "low", skip_serializing_if = "Option::is_none")]
    pub low: Option<models::FeeBreakdown>,
    #[serde(rename = "medium", skip_serializing_if = "Option::is_none")]
    pub medium: Option<models::FeeBreakdown>,
    #[serde(rename = "high", skip_serializing_if = "Option::is_none")]
    pub high: Option<models::FeeBreakdown>,
}

impl EstimatedFeeDetails {
    /// Optional detailed fee breakdown for high/medium/low estimates
    pub fn new() -> EstimatedFeeDetails {
        EstimatedFeeDetails {
            low: None,
            medium: None,
            high: None,
        }
    }
}
