// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ExecutionStepType {
    #[serde(rename = "APPROVE")]
    Approve,
    #[serde(rename = "PERMIT")]
    Permit,
    #[serde(rename = "CONTRACT_CALL")]
    ContractCall,
    #[serde(rename = "EXECUTE")]
    Execute,
    #[serde(rename = "SETTLEMENT")]
    Settlement,
}

impl std::fmt::Display for ExecutionStepType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Approve => write!(f, "APPROVE"),
            Self::Permit => write!(f, "PERMIT"),
            Self::ContractCall => write!(f, "CONTRACT_CALL"),
            Self::Execute => write!(f, "EXECUTE"),
            Self::Settlement => write!(f, "SETTLEMENT"),
        }
    }
}

impl Default for ExecutionStepType {
    fn default() -> ExecutionStepType {
        Self::Approve
    }
}
