// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// ExecutionRequestDetails : Order execution details
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ExecutionRequestDetails {
    #[serde(rename = "LIMIT")]
    Limit(models::LimitExecutionRequestDetails),
    #[serde(rename = "MARKET")]
    Market(models::MarketExecutionRequestDetails),
    #[serde(rename = "QUOTE")]
    Quote(models::QuoteExecutionWithRequoteRequestDetails),
}

impl Default for ExecutionRequestDetails {
    fn default() -> Self {
        Self::Limit(Default::default())
    }
}

/// Side of the order
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Side {
    #[serde(rename = "BUY")]
    Buy,
    #[serde(rename = "SELL")]
    Sell,
}

impl Default for Side {
    fn default() -> Side {
        Self::Buy
    }
}
