// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecutionStepStatus {
    #[serde(rename = "type")]
    pub r#type: models::ExecutionStepType,
    #[serde(rename = "status")]
    pub status: models::ExecutionStepStatusEnum,
    #[serde(rename = "fee", skip_serializing_if = "Option::is_none")]
    pub fee: Option<models::Fee>,
    #[serde(rename = "txId", skip_serializing_if = "Option::is_none")]
    pub tx_id: Option<String>,
    #[serde(rename = "txHash", skip_serializing_if = "Option::is_none")]
    pub tx_hash: Option<String>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<models::ExecutionStepError>,
}

impl ExecutionStepStatus {
    pub fn new(
        r#type: models::ExecutionStepType,
        status: models::ExecutionStepStatusEnum,
    ) -> ExecutionStepStatus {
        ExecutionStepStatus {
            r#type,
            status,
            fee: None,
            tx_id: None,
            tx_hash: None,
            error: None,
        }
    }
}
