// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Fee {
    /// The type of fee, such as ORDER, NETWORK, or SPREAD. - `ORDER`: Fee for
    /// executing the order. - `NETWORK`: Fee for network transactions. -
    /// `SPREAD`: Fee for the difference between buy and sell prices.
    #[serde(rename = "feeType")]
    pub fee_type: FeeType,
    /// The asset identifier for the fee.
    #[serde(rename = "assetId")]
    pub asset_id: String,
    #[serde(rename = "amountType")]
    pub amount_type: AmountType,
    /// Fee in basis points (1 = 0.01%, 10000 = 100%)
    #[serde(rename = "amount")]
    pub amount: f64,
}

impl Fee {
    pub fn new(fee_type: FeeType, asset_id: String, amount_type: AmountType, amount: f64) -> Fee {
        Fee {
            fee_type,
            asset_id,
            amount_type,
            amount,
        }
    }
}
/// The type of fee, such as ORDER, NETWORK, or SPREAD. - `ORDER`: Fee for
/// executing the order. - `NETWORK`: Fee for network transactions. - `SPREAD`:
/// Fee for the difference between buy and sell prices.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FeeType {
    #[serde(rename = "ORDER")]
    Order,
    #[serde(rename = "NETWORK")]
    Network,
    #[serde(rename = "SPREAD")]
    Spread,
}

impl Default for FeeType {
    fn default() -> FeeType {
        Self::Order
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AmountType {
    #[serde(rename = "BPS")]
    Bps,
}

impl Default for AmountType {
    fn default() -> AmountType {
        Self::Bps
    }
}
