// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// FeeBreakdownOneOf1 : Generic fee breakdown for other blockchains
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeeBreakdownOneOf1 {
    /// Base fee component
    #[serde(rename = "baseFee", skip_serializing_if = "Option::is_none")]
    pub base_fee: Option<String>,
    /// Priority fee component
    #[serde(rename = "priorityFee", skip_serializing_if = "Option::is_none")]
    pub priority_fee: Option<String>,
    /// Total fee amount
    #[serde(rename = "totalFee", skip_serializing_if = "Option::is_none")]
    pub total_fee: Option<String>,
}

impl FeeBreakdownOneOf1 {
    /// Generic fee breakdown for other blockchains
    pub fn new() -> FeeBreakdownOneOf1 {
        FeeBreakdownOneOf1 {
            base_fee: None,
            priority_fee: None,
            total_fee: None,
        }
    }
}
