// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// FeeBreakdownOneOf : Solana-specific fee breakdown
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeeBreakdownOneOf {
    /// Base fee for Solana transaction
    #[serde(rename = "baseFee", skip_serializing_if = "Option::is_none")]
    pub base_fee: Option<String>,
    /// Priority fee for Solana transaction
    #[serde(rename = "priorityFee", skip_serializing_if = "Option::is_none")]
    pub priority_fee: Option<String>,
    /// Rent fee for Solana account creation/storage
    #[serde(rename = "rent", skip_serializing_if = "Option::is_none")]
    pub rent: Option<String>,
    /// Total fee amount
    #[serde(rename = "totalFee", skip_serializing_if = "Option::is_none")]
    pub total_fee: Option<String>,
}

impl FeeBreakdownOneOf {
    /// Solana-specific fee breakdown
    pub fn new() -> FeeBreakdownOneOf {
        FeeBreakdownOneOf {
            base_fee: None,
            priority_fee: None,
            rent: None,
            total_fee: None,
        }
    }
}
