// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// FeeInfo : Details of the transaction fees.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeeInfo {
    /// The fee paid to the network.
    #[serde(rename = "networkFee", skip_serializing_if = "Option::is_none")]
    pub network_fee: Option<String>,
    /// The total fee deducted by the exchange from the actual requested amount
    /// (serviceFee = amount - netAmount).
    #[serde(rename = "serviceFee", skip_serializing_if = "Option::is_none")]
    pub service_fee: Option<String>,
    /// The amount of gas required by/paid to the network to process the
    /// transaction.
    #[serde(rename = "gasPrice", skip_serializing_if = "Option::is_none")]
    pub gas_price: Option<String>,
    /// Layer 1 network fee for Layer 2 blockchain transactions
    #[serde(rename = "L1networkFee", skip_serializing_if = "Option::is_none")]
    pub l1network_fee: Option<String>,
    /// Layer 2 network fee (gas price component for Layer 2 transactions)
    #[serde(rename = "L2networkFee", skip_serializing_if = "Option::is_none")]
    pub l2network_fee: Option<String>,
    /// Indicates whether the relay paid the fee.
    #[serde(rename = "paidByRelay", skip_serializing_if = "Option::is_none")]
    pub paid_by_relay: Option<bool>,
    /// Indicates whether the relay is the same tenant (`LOCAL`) or another
    /// tenant (`THIRD_PARTY`).
    #[serde(rename = "relayType", skip_serializing_if = "Option::is_none")]
    pub relay_type: Option<String>,
    /// The Vault account ID of the relay.
    #[serde(rename = "relayId", skip_serializing_if = "Option::is_none")]
    pub relay_id: Option<String>,
    /// The name of the tenant hosting the third-party relay.
    #[serde(rename = "relayName", skip_serializing_if = "Option::is_none")]
    pub relay_name: Option<String>,
    /// The USD equivalent value of the fee
    #[serde(rename = "feeUSD", skip_serializing_if = "Option::is_none")]
    pub fee_usd: Option<String>,
}

impl FeeInfo {
    /// Details of the transaction fees.
    pub fn new() -> FeeInfo {
        FeeInfo {
            network_fee: None,
            service_fee: None,
            gas_price: None,
            l1network_fee: None,
            l2network_fee: None,
            paid_by_relay: None,
            relay_type: None,
            relay_id: None,
            relay_name: None,
            fee_usd: None,
        }
    }
}
