// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum FiatDestination {
    #[serde(rename = "IBAN")]
    Iban(models::IbanDestination),
    #[serde(rename = "SWIFT")]
    Swift(models::SwiftDestination),
    #[serde(rename = "ACH")]
    Ach(models::AchDestination),
    #[serde(rename = "US_WIRE")]
    UsWire(models::UsWireDestination),
    #[serde(rename = "SPEI")]
    Spei(models::SpeiDestination),
    #[serde(rename = "SEPA")]
    Sepa(models::SepaDestination),
    #[serde(rename = "PIX")]
    Pix(models::PixDestination),
    #[serde(rename = "LOCAL_BANK_TRANSFER_AFRICA")]
    LocalBankTransferAfrica(models::LocalBankTransferAfricaDestination),
    #[serde(rename = "MOBILE_MONEY")]
    MobileMoney(models::MobileMoneyDestination),
}

impl Default for FiatDestination {
    fn default() -> Self {
        Self::Iban(Default::default())
    }
}
