// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// IbanPaymentInfo : IBAN payment information for European bank transfers
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IbanPaymentInfo {
    /// The given name (first name) of the account holder
    #[serde(rename = "accountHolderGivenName")]
    pub account_holder_given_name: String,
    /// The surname (last name) of the account holder
    #[serde(
        rename = "accountHolderSurname",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_holder_surname: Option<String>,
    /// The city where the account holder resides
    #[serde(rename = "accountHolderCity")]
    pub account_holder_city: String,
    /// The country where the account holder resides (ISO 3166-1 alpha-2 code)
    #[serde(rename = "accountHolderCountry")]
    pub account_holder_country: String,
    /// The primary address line of the account holder
    #[serde(rename = "accountHolderAddress1")]
    pub account_holder_address1: String,
    /// The secondary address line of the account holder (optional)
    #[serde(
        rename = "accountHolderAddress2",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_holder_address2: Option<String>,
    /// The district or region where the account holder resides
    #[serde(
        rename = "accountHolderDistrict",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_holder_district: Option<String>,
    /// The postal code of the account holder's address
    #[serde(rename = "accountHolderPostalCode")]
    pub account_holder_postal_code: String,
    /// The International Bank Account Number (IBAN)
    #[serde(rename = "iban")]
    pub iban: String,
    /// The city associated with the IBAN
    #[serde(rename = "ibanCity")]
    pub iban_city: String,
    /// The country associated with the IBAN (ISO 3166-1 alpha-2 code)
    #[serde(rename = "ibanCountry")]
    pub iban_country: String,
}

impl IbanPaymentInfo {
    /// IBAN payment information for European bank transfers
    pub fn new(
        account_holder_given_name: String,
        account_holder_city: String,
        account_holder_country: String,
        account_holder_address1: String,
        account_holder_postal_code: String,
        iban: String,
        iban_city: String,
        iban_country: String,
    ) -> IbanPaymentInfo {
        IbanPaymentInfo {
            account_holder_given_name,
            account_holder_surname: None,
            account_holder_city,
            account_holder_country,
            account_holder_address1,
            account_holder_address2: None,
            account_holder_district: None,
            account_holder_postal_code,
            iban,
            iban_city,
            iban_country,
        }
    }
}
