// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// InitiatorConfigV2 : Policy rule initiator configuration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InitiatorConfigV2 {
    /// List of user IDs
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<String>>,
    /// List of policy group IDs
    #[serde(rename = "groups", skip_serializing_if = "Option::is_none")]
    pub groups: Option<Vec<String>>,
    #[serde(rename = "services", skip_serializing_if = "Option::is_none")]
    pub services: Option<Vec<String>>,
    #[serde(rename = "fbAdminGroups", skip_serializing_if = "Option::is_none")]
    pub fb_admin_groups: Option<Vec<String>>,
    #[serde(rename = "exchange", skip_serializing_if = "Option::is_none")]
    pub exchange: Option<Vec<String>>,
    #[serde(rename = "operator")]
    pub operator: models::PolicyOperatorV2,
}

impl InitiatorConfigV2 {
    /// Policy rule initiator configuration
    pub fn new(operator: models::PolicyOperatorV2) -> InitiatorConfigV2 {
        InitiatorConfigV2 {
            users: None,
            groups: None,
            services: None,
            fb_admin_groups: None,
            exchange: None,
            operator,
        }
    }
}
