// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// LbtPaymentInfo : LBT (Lebanese Bank Transfer) payment information for
/// Lebanese bank transfers
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LbtPaymentInfo {
    /// The payment rail type for Lebanese bank transfers
    #[serde(rename = "rail")]
    pub rail: Rail,
    /// The addressing system used for Lebanese bank transfers (Bank Account
    /// Number)
    #[serde(rename = "addressingSystem")]
    pub addressing_system: AddressingSystem,
    /// The given name (first name) of the account holder
    #[serde(rename = "accountHolderGivenName")]
    pub account_holder_given_name: String,
    /// The surname (last name) of the account holder
    #[serde(rename = "accountHolderSurname")]
    pub account_holder_surname: String,
    /// The country for the transfer (ISO 3166-1 alpha-2 code)
    #[serde(rename = "country")]
    pub country: String,
    /// The bank account number
    #[serde(rename = "accountNumber")]
    pub account_number: String,
    /// The name of the bank
    #[serde(rename = "bankName")]
    pub bank_name: String,
    /// The bank code or identifier
    #[serde(rename = "bankCode")]
    pub bank_code: String,
}

impl LbtPaymentInfo {
    /// LBT (Lebanese Bank Transfer) payment information for Lebanese bank
    /// transfers
    pub fn new(
        rail: Rail,
        addressing_system: AddressingSystem,
        account_holder_given_name: String,
        account_holder_surname: String,
        country: String,
        account_number: String,
        bank_name: String,
        bank_code: String,
    ) -> LbtPaymentInfo {
        LbtPaymentInfo {
            rail,
            addressing_system,
            account_holder_given_name,
            account_holder_surname,
            country,
            account_number,
            bank_name,
            bank_code,
        }
    }
}
/// The payment rail type for Lebanese bank transfers
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Rail {
    #[serde(rename = "LBT")]
    Lbt,
}

impl Default for Rail {
    fn default() -> Rail {
        Self::Lbt
    }
}
/// The addressing system used for Lebanese bank transfers (Bank Account Number)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AddressingSystem {
    #[serde(rename = "BAN")]
    Ban,
}

impl Default for AddressingSystem {
    fn default() -> AddressingSystem {
        Self::Ban
    }
}
