// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LimitExecutionResponseDetails {
    /// Side of the order
    #[serde(rename = "side")]
    pub side: Side,
    /// Amount to convert
    #[serde(rename = "baseAmount")]
    pub base_amount: String,
    /// Source asset identifier
    #[serde(rename = "baseAssetId")]
    pub base_asset_id: String,
    #[serde(rename = "baseAssetRail", skip_serializing_if = "Option::is_none")]
    pub base_asset_rail: Option<models::TransferRail>,
    /// Target asset identifier
    #[serde(rename = "quoteAssetId")]
    pub quote_asset_id: String,
    #[serde(rename = "quoteAssetRail", skip_serializing_if = "Option::is_none")]
    pub quote_asset_rail: Option<models::TransferRail>,
    /// Order type for limit orders
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "timeInForce")]
    pub time_in_force: models::TimeInForce,
    /// Price for limit orders
    #[serde(rename = "limitPrice")]
    pub limit_price: String,
}

impl LimitExecutionResponseDetails {
    pub fn new(
        side: Side,
        base_amount: String,
        base_asset_id: String,
        quote_asset_id: String,
        r#type: Type,
        time_in_force: models::TimeInForce,
        limit_price: String,
    ) -> LimitExecutionResponseDetails {
        LimitExecutionResponseDetails {
            side,
            base_amount,
            base_asset_id,
            base_asset_rail: None,
            quote_asset_id,
            quote_asset_rail: None,
            r#type,
            time_in_force,
            limit_price,
        }
    }
}
/// Side of the order
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Side {
    #[serde(rename = "BUY")]
    Buy,
    #[serde(rename = "SELL")]
    Sell,
}

impl Default for Side {
    fn default() -> Side {
        Self::Buy
    }
}
/// Order type for limit orders
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "LIMIT")]
    Limit,
}

impl Default for Type {
    fn default() -> Type {
        Self::Limit
    }
}
