// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocalBankTransferAfricaAddress {
    #[serde(rename = "accountHolder")]
    pub account_holder: models::AccountHolderDetails,
    #[serde(rename = "accountNumber")]
    pub account_number: String,
    /// Name of the bank
    #[serde(rename = "bankName")]
    pub bank_name: String,
    /// Internal bank identifier
    #[serde(rename = "bankCode")]
    pub bank_code: String,
}

impl LocalBankTransferAfricaAddress {
    pub fn new(
        account_holder: models::AccountHolderDetails,
        account_number: String,
        bank_name: String,
        bank_code: String,
    ) -> LocalBankTransferAfricaAddress {
        LocalBankTransferAfricaAddress {
            account_holder,
            account_number,
            bank_name,
            bank_code,
        }
    }
}
