// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Manifest {
    #[serde(rename = "assetTypes")]
    pub asset_types: Vec<AssetTypes>,
    #[serde(rename = "capabilities")]
    pub capabilities: Vec<models::Capability>,
}

impl Manifest {
    pub fn new(asset_types: Vec<AssetTypes>, capabilities: Vec<models::Capability>) -> Manifest {
        Manifest {
            asset_types,
            capabilities,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AssetTypes {
    #[serde(rename = "DIGITAL")]
    Digital,
    #[serde(rename = "FIAT")]
    Fiat,
}

impl Default for AssetTypes {
    fn default() -> AssetTypes {
        Self::Digital
    }
}
