// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarketRequoteRequestDetails {
    /// Indicates that the order should be re-quoted if the original quote is
    /// expired. This will lead to a market order.
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl MarketRequoteRequestDetails {
    pub fn new(r#type: Type) -> MarketRequoteRequestDetails {
        MarketRequoteRequestDetails { r#type }
    }
}
/// Indicates that the order should be re-quoted if the original quote is
/// expired. This will lead to a market order.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "MARKET")]
    Market,
}

impl Default for Type {
    fn default() -> Type {
        Self::Market
    }
}
