// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MobileMoneyAddress {
    #[serde(rename = "accountHolder")]
    pub account_holder: models::AccountHolderDetails,
    /// Mobile phone number in E.164 format
    #[serde(rename = "mobilePhoneNumber")]
    pub mobile_phone_number: String,
    /// Mobile money provider
    #[serde(rename = "provider")]
    pub provider: Provider,
    /// Beneficiary document identification (may be required)
    #[serde(
        rename = "beneficiaryDocumentId",
        skip_serializing_if = "Option::is_none"
    )]
    pub beneficiary_document_id: Option<String>,
    /// Relationship to beneficiary for AML purposes
    #[serde(
        rename = "beneficiaryRelationship",
        skip_serializing_if = "Option::is_none"
    )]
    pub beneficiary_relationship: Option<String>,
}

impl MobileMoneyAddress {
    pub fn new(
        account_holder: models::AccountHolderDetails,
        mobile_phone_number: String,
        provider: Provider,
    ) -> MobileMoneyAddress {
        MobileMoneyAddress {
            account_holder,
            mobile_phone_number,
            provider,
            beneficiary_document_id: None,
            beneficiary_relationship: None,
        }
    }
}
/// Mobile money provider
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Provider {
    #[serde(rename = "m-pesa")]
    MPesa,
    #[serde(rename = "airtel")]
    Airtel,
    #[serde(rename = "mtn")]
    Mtn,
    #[serde(rename = "tigo")]
    Tigo,
    #[serde(rename = "orange")]
    Orange,
}

impl Default for Provider {
    fn default() -> Provider {
        Self::MPesa
    }
}
