// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// MomoPaymentInfo : Mobile Money (MOMO) payment information for African mobile
/// payment services
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MomoPaymentInfo {
    /// The payment rail type for mobile money transfers
    #[serde(rename = "rail")]
    pub rail: Rail,
    /// The addressing system used for mobile money transfers
    #[serde(rename = "addressingSystem")]
    pub addressing_system: AddressingSystem,
    /// The given name (first name) of the account holder
    #[serde(rename = "accountHolderGivenName")]
    pub account_holder_given_name: String,
    /// The surname (last name) of the account holder
    #[serde(rename = "accountHolderSurname")]
    pub account_holder_surname: String,
    /// The country for the transfer (ISO 3166-1 alpha-2 code)
    #[serde(rename = "country")]
    pub country: String,
    /// The mobile phone number associated with the mobile money account
    #[serde(rename = "mobilePhoneNumber")]
    pub mobile_phone_number: String,
    /// The mobile money service provider
    #[serde(rename = "provider")]
    pub provider: Provider,
    /// The document ID of the beneficiary
    #[serde(
        rename = "beneficiaryDocumentId",
        skip_serializing_if = "Option::is_none"
    )]
    pub beneficiary_document_id: Option<String>,
    /// The relationship between sender and beneficiary
    #[serde(
        rename = "beneficiaryRelationship",
        skip_serializing_if = "Option::is_none"
    )]
    pub beneficiary_relationship: Option<String>,
}

impl MomoPaymentInfo {
    /// Mobile Money (MOMO) payment information for African mobile payment
    /// services
    pub fn new(
        rail: Rail,
        addressing_system: AddressingSystem,
        account_holder_given_name: String,
        account_holder_surname: String,
        country: String,
        mobile_phone_number: String,
        provider: Provider,
    ) -> MomoPaymentInfo {
        MomoPaymentInfo {
            rail,
            addressing_system,
            account_holder_given_name,
            account_holder_surname,
            country,
            mobile_phone_number,
            provider,
            beneficiary_document_id: None,
            beneficiary_relationship: None,
        }
    }
}
/// The payment rail type for mobile money transfers
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Rail {
    #[serde(rename = "MOMO")]
    Momo,
}

impl Default for Rail {
    fn default() -> Rail {
        Self::Momo
    }
}
/// The addressing system used for mobile money transfers
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AddressingSystem {
    #[serde(rename = "MOMO")]
    Momo,
}

impl Default for AddressingSystem {
    fn default() -> AddressingSystem {
        Self::Momo
    }
}
/// The mobile money service provider
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Provider {
    #[serde(rename = "M_PESA")]
    MPesa,
    #[serde(rename = "AIRTEL")]
    Airtel,
    #[serde(rename = "MTN")]
    Mtn,
    #[serde(rename = "TIGO")]
    Tigo,
}

impl Default for Provider {
    fn default() -> Provider {
        Self::MPesa
    }
}
