// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationAttempt {
    /// The time when the attempt was sent in milliseconds.
    #[serde(rename = "sentTime")]
    pub sent_time: i64,
    /// The duration of the attempt in milliseconds.
    #[serde(rename = "duration")]
    pub duration: i32,
    /// The response code of the attempt, when missing refer to failureReason.
    #[serde(rename = "responseCode", skip_serializing_if = "Option::is_none")]
    pub response_code: Option<i32>,
    /// The request failure reason in case responseCode is missing.
    #[serde(rename = "failureReason", skip_serializing_if = "Option::is_none")]
    pub failure_reason: Option<FailureReason>,
}

impl NotificationAttempt {
    pub fn new(sent_time: i64, duration: i32) -> NotificationAttempt {
        NotificationAttempt {
            sent_time,
            duration,
            response_code: None,
            failure_reason: None,
        }
    }
}
/// The request failure reason in case responseCode is missing.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FailureReason {
    #[serde(rename = "TIMED_OUT")]
    TimedOut,
    #[serde(rename = "NO_RESPONSE")]
    NoResponse,
}

impl Default for FailureReason {
    fn default() -> FailureReason {
        Self::TimedOut
    }
}
