// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OneTimeAddressReference {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
}

impl OneTimeAddressReference {
    pub fn new(r#type: Type, address: String) -> OneTimeAddressReference {
        OneTimeAddressReference {
            r#type,
            address,
            tag: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "ONE_TIME_ADDRESS")]
    OneTimeAddress,
}

impl Default for Type {
    fn default() -> Type {
        Self::OneTimeAddress
    }
}
