// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// ParticipantsIdentification : KYC/AML participant identification
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParticipantsIdentification {
    #[serde(rename = "originator", skip_serializing_if = "Option::is_none")]
    pub originator: Option<models::Identification>,
    #[serde(rename = "beneficiary", skip_serializing_if = "Option::is_none")]
    pub beneficiary: Option<models::Identification>,
}

impl ParticipantsIdentification {
    /// KYC/AML participant identification
    pub fn new() -> ParticipantsIdentification {
        ParticipantsIdentification {
            originator: None,
            beneficiary: None,
        }
    }
}
