// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ParticipantRelationshipType {
    #[serde(rename = "FirstParty")]
    FirstParty,
    #[serde(rename = "SecondParty")]
    SecondParty,
    #[serde(rename = "ThirdParty")]
    ThirdParty,
}

impl std::fmt::Display for ParticipantRelationshipType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::FirstParty => write!(f, "FirstParty"),
            Self::SecondParty => write!(f, "SecondParty"),
            Self::ThirdParty => write!(f, "ThirdParty"),
        }
    }
}

impl Default for ParticipantRelationshipType {
    fn default() -> ParticipantRelationshipType {
        Self::FirstParty
    }
}
