// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PeerType {
    #[serde(rename = "VAULT_ACCOUNT")]
    VaultAccount,
    #[serde(rename = "EXCHANGE_ACCOUNT")]
    ExchangeAccount,
    #[serde(rename = "INTERNAL_WALLET")]
    InternalWallet,
    #[serde(rename = "EXTERNAL_WALLET")]
    ExternalWallet,
    #[serde(rename = "FIAT_ACCOUNT")]
    FiatAccount,
}

impl std::fmt::Display for PeerType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::VaultAccount => write!(f, "VAULT_ACCOUNT"),
            Self::ExchangeAccount => write!(f, "EXCHANGE_ACCOUNT"),
            Self::InternalWallet => write!(f, "INTERNAL_WALLET"),
            Self::ExternalWallet => write!(f, "EXTERNAL_WALLET"),
            Self::FiatAccount => write!(f, "FIAT_ACCOUNT"),
        }
    }
}

impl Default for PeerType {
    fn default() -> PeerType {
        Self::VaultAccount
    }
}
