// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// PolicyAndValidationResponseV2 : Policy validation
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PolicyAndValidationResponseV2 {
    #[serde(rename = "policy")]
    pub policy: models::PolicyResponseV2,
    #[serde(rename = "validation")]
    pub validation: models::PolicyValidationV2,
}

impl PolicyAndValidationResponseV2 {
    /// Policy validation
    pub fn new(
        policy: models::PolicyResponseV2,
        validation: models::PolicyValidationV2,
    ) -> PolicyAndValidationResponseV2 {
        PolicyAndValidationResponseV2 { policy, validation }
    }
}
