// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// PolicyTypeV2 : Policy type enumeration
/// Policy type enumeration
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PolicyTypeV2 {
    #[serde(rename = "TRANSFER")]
    Transfer,
    #[serde(rename = "STAKE")]
    Stake,
    #[serde(rename = "CONTRACT_CALL")]
    ContractCall,
    #[serde(rename = "TYPED_MESSAGE")]
    TypedMessage,
    #[serde(rename = "APPROVE")]
    Approve,
    #[serde(rename = "MINT")]
    Mint,
    #[serde(rename = "BURN")]
    Burn,
    #[serde(rename = "RAW")]
    Raw,
    #[serde(rename = "COMPLIANCE")]
    Compliance,
    #[serde(rename = "DEPLOYMENT")]
    Deployment,
    #[serde(rename = "PROGRAM_CALL")]
    ProgramCall,
    #[serde(rename = "DAPP_CONNECTION")]
    DappConnection,
    #[serde(rename = "UPGRADE")]
    Upgrade,
    #[serde(rename = "ORDER")]
    Order,
    #[serde(rename = "AML_CHAINALYSIS_V2_SCREENING")]
    AmlChainalysisV2Screening,
    #[serde(rename = "AML_CHAINALYSIS_V2_POST_SCREENING")]
    AmlChainalysisV2PostScreening,
    #[serde(rename = "AML_ELLIPTIC_HOLISTIC_SCREENING")]
    AmlEllipticHolisticScreening,
    #[serde(rename = "AML_ELLIPTIC_HOLISTIC_POST_SCREENING")]
    AmlEllipticHolisticPostScreening,
    #[serde(rename = "TR_NOTABENE_SCREENING")]
    TrNotabeneScreening,
    #[serde(rename = "TR_NOTABENE_POST_SCREENING")]
    TrNotabenePostScreening,
}

impl std::fmt::Display for PolicyTypeV2 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Transfer => write!(f, "TRANSFER"),
            Self::Stake => write!(f, "STAKE"),
            Self::ContractCall => write!(f, "CONTRACT_CALL"),
            Self::TypedMessage => write!(f, "TYPED_MESSAGE"),
            Self::Approve => write!(f, "APPROVE"),
            Self::Mint => write!(f, "MINT"),
            Self::Burn => write!(f, "BURN"),
            Self::Raw => write!(f, "RAW"),
            Self::Compliance => write!(f, "COMPLIANCE"),
            Self::Deployment => write!(f, "DEPLOYMENT"),
            Self::ProgramCall => write!(f, "PROGRAM_CALL"),
            Self::DappConnection => write!(f, "DAPP_CONNECTION"),
            Self::Upgrade => write!(f, "UPGRADE"),
            Self::Order => write!(f, "ORDER"),
            Self::AmlChainalysisV2Screening => write!(f, "AML_CHAINALYSIS_V2_SCREENING"),
            Self::AmlChainalysisV2PostScreening => write!(f, "AML_CHAINALYSIS_V2_POST_SCREENING"),
            Self::AmlEllipticHolisticScreening => write!(f, "AML_ELLIPTIC_HOLISTIC_SCREENING"),
            Self::AmlEllipticHolisticPostScreening => {
                write!(f, "AML_ELLIPTIC_HOLISTIC_POST_SCREENING")
            }
            Self::TrNotabeneScreening => write!(f, "TR_NOTABENE_SCREENING"),
            Self::TrNotabenePostScreening => write!(f, "TR_NOTABENE_POST_SCREENING"),
        }
    }
}

impl Default for PolicyTypeV2 {
    fn default() -> PolicyTypeV2 {
        Self::Transfer
    }
}
