// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// PolicyResponseV2 : Response object for policy operations
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PolicyResponseV2 {
    /// A set of policy rules
    #[serde(rename = "rules")]
    pub rules: Vec<models::PolicyRuleV2>,
    #[serde(rename = "metadata")]
    pub metadata: models::PolicyMetadataV2,
}

impl PolicyResponseV2 {
    /// Response object for policy operations
    pub fn new(
        rules: Vec<models::PolicyRuleV2>,
        metadata: models::PolicyMetadataV2,
    ) -> PolicyResponseV2 {
        PolicyResponseV2 { rules, metadata }
    }
}
