// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostalAddress {
    #[serde(rename = "streetName")]
    pub street_name: String,
    #[serde(rename = "buildingNumber")]
    pub building_number: String,
    #[serde(rename = "postalCode")]
    pub postal_code: String,
    #[serde(rename = "city")]
    pub city: String,
    #[serde(rename = "subdivision")]
    pub subdivision: String,
    #[serde(rename = "district")]
    pub district: String,
    #[serde(rename = "country")]
    pub country: String,
}

impl PostalAddress {
    pub fn new(
        street_name: String,
        building_number: String,
        postal_code: String,
        city: String,
        subdivision: String,
        district: String,
        country: String,
    ) -> PostalAddress {
        PostalAddress {
            street_name,
            building_number,
            postal_code,
            city,
            subdivision,
            district,
            country,
        }
    }
}
