// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// ProgramCallConfigV2 : Program call configuration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProgramCallConfigV2 {
    /// Whether Solana program calls are allowed
    #[serde(rename = "allowedSolanaProgramCalls")]
    pub allowed_solana_program_calls: AllowedSolanaProgramCalls,
}

impl ProgramCallConfigV2 {
    /// Program call configuration
    pub fn new(allowed_solana_program_calls: AllowedSolanaProgramCalls) -> ProgramCallConfigV2 {
        ProgramCallConfigV2 {
            allowed_solana_program_calls,
        }
    }
}
/// Whether Solana program calls are allowed
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AllowedSolanaProgramCalls {
    #[serde(rename = "*")]
    Star,
    #[serde(rename = "WHITELISTED")]
    Whitelisted,
}

impl Default for AllowedSolanaProgramCalls {
    fn default() -> AllowedSolanaProgramCalls {
        Self::Star
    }
}
