// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// PublishDraftRequestV2 : Request schema for publishing draft with policy
/// types and draft ID
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublishDraftRequestV2 {
    #[serde(rename = "policyTypes")]
    pub policy_types: Vec<models::PolicyTypeV2>,
    /// The ID of the draft to publish
    #[serde(rename = "draftId")]
    pub draft_id: String,
}

impl PublishDraftRequestV2 {
    /// Request schema for publishing draft with policy types and draft ID
    pub fn new(policy_types: Vec<models::PolicyTypeV2>, draft_id: String) -> PublishDraftRequestV2 {
        PublishDraftRequestV2 {
            policy_types,
            draft_id,
        }
    }
}
