// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuoteExecutionWithRequoteResponseDetails {
    /// Order type for quote orders
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Quote ID for quote orders
    #[serde(rename = "quoteId")]
    pub quote_id: String,
    /// Quote amount for quote orders
    #[serde(rename = "quoteAmount")]
    pub quote_amount: String,
    /// Side of the order
    #[serde(rename = "side")]
    pub side: Side,
    /// Amount to convert
    #[serde(rename = "baseAmount")]
    pub base_amount: String,
    /// Source asset identifier
    #[serde(rename = "baseAssetId")]
    pub base_asset_id: String,
    #[serde(rename = "baseAssetRail", skip_serializing_if = "Option::is_none")]
    pub base_asset_rail: Option<models::TransferRail>,
    /// Target asset identifier
    #[serde(rename = "quoteAssetId")]
    pub quote_asset_id: String,
    #[serde(rename = "quoteAssetRail", skip_serializing_if = "Option::is_none")]
    pub quote_asset_rail: Option<models::TransferRail>,
    #[serde(rename = "reQuote", skip_serializing_if = "Option::is_none")]
    pub re_quote: Option<models::QuoteExecutionWithRequoteResponseDetailsAllOfReQuote>,
}

impl QuoteExecutionWithRequoteResponseDetails {
    pub fn new(
        r#type: Type,
        quote_id: String,
        quote_amount: String,
        side: Side,
        base_amount: String,
        base_asset_id: String,
        quote_asset_id: String,
    ) -> QuoteExecutionWithRequoteResponseDetails {
        QuoteExecutionWithRequoteResponseDetails {
            r#type,
            quote_id,
            quote_amount,
            side,
            base_amount,
            base_asset_id,
            base_asset_rail: None,
            quote_asset_id,
            quote_asset_rail: None,
            re_quote: None,
        }
    }
}
/// Order type for quote orders
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "QUOTE")]
    Quote,
}

impl Default for Type {
    fn default() -> Type {
        Self::Quote
    }
}
/// Side of the order
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Side {
    #[serde(rename = "BUY")]
    Buy,
    #[serde(rename = "SELL")]
    Sell,
}

impl Default for Side {
    fn default() -> Side {
        Self::Buy
    }
}
