// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Quote {
    #[serde(rename = "via")]
    pub via: models::AccessType,
    #[serde(rename = "id")]
    pub id: String,
    /// Indicates this is an indicative quote
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "quoteAssetId")]
    pub quote_asset_id: String,
    #[serde(rename = "baseAssetId")]
    pub base_asset_id: String,
    #[serde(rename = "baseAmount")]
    pub base_amount: String,
    #[serde(rename = "quoteAmount")]
    pub quote_amount: String,
    #[serde(rename = "priceImpact", skip_serializing_if = "Option::is_none")]
    pub price_impact: Option<f64>,
    #[serde(rename = "quoteMinAmount", skip_serializing_if = "Option::is_none")]
    pub quote_min_amount: Option<String>,
    #[serde(rename = "executionSteps", skip_serializing_if = "Option::is_none")]
    pub execution_steps: Option<Vec<models::ExecutionStepDetails>>,
    #[serde(rename = "generalFees", skip_serializing_if = "Option::is_none")]
    pub general_fees: Option<Vec<models::Fee>>,
    /// Side of the order
    #[serde(rename = "side")]
    pub side: Side,
    /// ISO 8601 timestamp of the expiration time of the quote.
    #[serde(rename = "expiresAt")]
    pub expires_at: String,
}

impl Quote {
    pub fn new(
        via: models::AccessType,
        id: String,
        r#type: Type,
        quote_asset_id: String,
        base_asset_id: String,
        base_amount: String,
        quote_amount: String,
        side: Side,
        expires_at: String,
    ) -> Quote {
        Quote {
            via,
            id,
            r#type,
            quote_asset_id,
            base_asset_id,
            base_amount,
            quote_amount,
            price_impact: None,
            quote_min_amount: None,
            execution_steps: None,
            general_fees: None,
            side,
            expires_at,
        }
    }
}
/// Indicates this is an indicative quote
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "INDICATIVE")]
    Indicative,
}

impl Default for Type {
    fn default() -> Type {
        Self::Indicative
    }
}
/// Side of the order
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Side {
    #[serde(rename = "BUY")]
    Buy,
    #[serde(rename = "SELL")]
    Sell,
}

impl Default for Side {
    fn default() -> Side {
        Self::Buy
    }
}
