// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuoteExecutionRequestDetails {
    /// Order type for quote orders
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Quote ID for quote orders
    #[serde(rename = "quoteId")]
    pub quote_id: String,
}

impl QuoteExecutionRequestDetails {
    pub fn new(r#type: Type, quote_id: String) -> QuoteExecutionRequestDetails {
        QuoteExecutionRequestDetails { r#type, quote_id }
    }
}
/// Order type for quote orders
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "QUOTE")]
    Quote,
}

impl Default for Type {
    fn default() -> Type {
        Self::Quote
    }
}
