// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResendFailedNotificationsRequest {
    /// (optional) Start time for the resend window in milliseconds since epoch
    /// up to 24 hours before the current time - Default if missing means 24
    /// hours before the current time in milliseconds since epoch - Maximum
    /// value is current time in milliseconds since epoch - Minimum value is 24
    /// hours before the current time in milliseconds since epoch
    #[serde(rename = "startTime", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<f64>,
    /// (optional) Event types to resend, default is all event types - Default
    /// if missing means all events will be included - Empty array means all
    /// events will be included
    #[serde(rename = "events", skip_serializing_if = "Option::is_none")]
    pub events: Option<Vec<String>>,
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<models::WebhookEvent>,
}

impl ResendFailedNotificationsRequest {
    pub fn new() -> ResendFailedNotificationsRequest {
        ResendFailedNotificationsRequest {
            start_time: None,
            events: None,
            items: None,
        }
    }
}
