// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResendFailedNotificationsJobStatusResponse {
    /// Bulk resend job ID
    #[serde(rename = "jobId")]
    pub job_id: String,
    /// Bulk resend job status
    #[serde(rename = "status")]
    pub status: Status,
    /// Number of notifications processed
    #[serde(rename = "processed")]
    pub processed: f64,
    /// Total number of notifications to process
    #[serde(rename = "total")]
    pub total: f64,
}

impl ResendFailedNotificationsJobStatusResponse {
    pub fn new(
        job_id: String,
        status: Status,
        processed: f64,
        total: f64,
    ) -> ResendFailedNotificationsJobStatusResponse {
        ResendFailedNotificationsJobStatusResponse {
            job_id,
            status,
            processed,
            total,
        }
    }
}
/// Bulk resend job status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "QUEUED")]
    Queued,
    #[serde(rename = "IN_PROGRESS")]
    InProgress,
    #[serde(rename = "COMPLETED")]
    Completed,
    #[serde(rename = "FAILED")]
    Failed,
}

impl Default for Status {
    fn default() -> Status {
        Self::Queued
    }
}
