// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RetryRequoteRequestDetails {
    /// Indicates that the order should be re-quoted if the original quote is
    /// expired, trying to match the original quote.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// If quote is expired, how many times to re-generate new quotes to try
    /// having the order executed as in the original quote.
    #[serde(rename = "count")]
    pub count: f64,
    /// Slippage tolerance in basis points (bps) for quote orders - 1 is 0.01%
    /// and 10000 is 100%
    #[serde(rename = "slippageBps", skip_serializing_if = "Option::is_none")]
    pub slippage_bps: Option<f64>,
}

impl RetryRequoteRequestDetails {
    pub fn new(r#type: Type, count: f64) -> RetryRequoteRequestDetails {
        RetryRequoteRequestDetails {
            r#type,
            count,
            slippage_bps: None,
        }
    }
}
/// Indicates that the order should be re-quoted if the original quote is
/// expired, trying to match the original quote.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "RETRY")]
    Retry,
}

impl Default for Type {
    fn default() -> Type {
        Self::Retry
    }
}
