// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// ScreeningMetadataConfigV2 : Screening metadata configuration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScreeningMetadataConfigV2 {
    /// Direction of transaction
    #[serde(rename = "direction")]
    pub direction: Direction,
    /// Screening provider
    #[serde(
        rename = "provider",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub provider: Option<Option<Provider>>,
    /// Risk rating threshold
    #[serde(rename = "riskRating", skip_serializing_if = "Option::is_none")]
    pub risk_rating: Option<RiskRating>,
    /// Risk score threshold
    #[serde(rename = "riskScore", skip_serializing_if = "Option::is_none")]
    pub risk_score: Option<String>,
    /// Exposure type
    #[serde(rename = "exposureType", skip_serializing_if = "Option::is_none")]
    pub exposure_type: Option<ExposureType>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<Vec<String>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<Vec<String>>,
    #[serde(rename = "categoryId", skip_serializing_if = "Option::is_none")]
    pub category_id: Option<Vec<String>>,
    /// Transaction status
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// Source address
    #[serde(rename = "sourceAddress", skip_serializing_if = "Option::is_none")]
    pub source_address: Option<String>,
    /// Destination address
    #[serde(rename = "destAddress", skip_serializing_if = "Option::is_none")]
    pub dest_address: Option<String>,
}

impl ScreeningMetadataConfigV2 {
    /// Screening metadata configuration
    pub fn new(direction: Direction) -> ScreeningMetadataConfigV2 {
        ScreeningMetadataConfigV2 {
            direction,
            provider: None,
            risk_rating: None,
            risk_score: None,
            exposure_type: None,
            category: None,
            name: None,
            category_id: None,
            status: None,
            source_address: None,
            dest_address: None,
        }
    }
}
/// Direction of transaction
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Direction {
    #[serde(rename = "INBOUND")]
    Inbound,
    #[serde(rename = "OUTBOUND")]
    Outbound,
    #[serde(rename = "ANY")]
    Any,
}

impl Default for Direction {
    fn default() -> Direction {
        Self::Inbound
    }
}
/// Screening provider
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Provider {
    #[serde(rename = "CHAINALYSIS")]
    Chainalysis,
    #[serde(rename = "CHAINALYSIS_V2")]
    ChainalysisV2,
    #[serde(rename = "ELLIPTIC")]
    Elliptic,
    #[serde(rename = "ELLIPTIC_HOLISTIC")]
    EllipticHolistic,
    #[serde(rename = "NOTABENE")]
    Notabene,
}

impl Default for Provider {
    fn default() -> Provider {
        Self::Chainalysis
    }
}
/// Risk rating threshold
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RiskRating {
    #[serde(rename = "LOW")]
    Low,
    #[serde(rename = "MEDIUM")]
    Medium,
    #[serde(rename = "HIGH")]
    High,
    #[serde(rename = "SEVERE")]
    Severe,
    #[serde(rename = "ANY")]
    Any,
}

impl Default for RiskRating {
    fn default() -> RiskRating {
        Self::Low
    }
}
/// Exposure type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ExposureType {
    #[serde(rename = "DIRECT")]
    Direct,
    #[serde(rename = "INDIRECT")]
    Indirect,
    #[serde(rename = "ANY")]
    Any,
}

impl Default for ExposureType {
    fn default() -> ExposureType {
        Self::Direct
    }
}
/// Transaction status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "COMPLETED")]
    Completed,
    #[serde(rename = "PENDING")]
    Pending,
    #[serde(rename = "REJECTED")]
    Rejected,
    #[serde(rename = "FAILED")]
    Failed,
    #[serde(rename = "CANCELED")]
    Canceled,
    #[serde(rename = "BLOCKING_TIME_EXPIRED")]
    BlockingTimeExpired,
}

impl Default for Status {
    fn default() -> Status {
        Self::Completed
    }
}
