// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SepaAddress {
    #[serde(rename = "accountHolder")]
    pub account_holder: models::AccountHolderDetails,
    #[serde(rename = "iban")]
    pub iban: String,
    /// Bank Identifier Code (SWIFT/BIC)
    #[serde(rename = "bic", skip_serializing_if = "Option::is_none")]
    pub bic: Option<String>,
    #[serde(rename = "bankName", skip_serializing_if = "Option::is_none")]
    pub bank_name: Option<String>,
    #[serde(rename = "bankBranch", skip_serializing_if = "Option::is_none")]
    pub bank_branch: Option<String>,
    #[serde(rename = "bankAddress", skip_serializing_if = "Option::is_none")]
    pub bank_address: Option<String>,
    /// ISO purpose code for the transfer
    #[serde(rename = "purposeCode", skip_serializing_if = "Option::is_none")]
    pub purpose_code: Option<String>,
    /// Beneficiary tax identification number
    #[serde(rename = "taxId", skip_serializing_if = "Option::is_none")]
    pub tax_id: Option<String>,
}

impl SepaAddress {
    pub fn new(account_holder: models::AccountHolderDetails, iban: String) -> SepaAddress {
        SepaAddress {
            account_holder,
            iban,
            bic: None,
            bank_name: None,
            bank_branch: None,
            bank_address: None,
            purpose_code: None,
            tax_id: None,
        }
    }
}
