// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// Settlement : Settlement configuration for the order
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Settlement {
    #[serde(rename = "PREFUNDED")]
    Prefunded(models::PrefundedSettlement),
    #[serde(rename = "DVP")]
    Dvp(models::DvpSettlement),
    #[serde(rename = "POST_ORDER")]
    PostOrder(models::PostOrderSettlement),
}

impl Default for Settlement {
    fn default() -> Self {
        Self::Prefunded(Default::default())
    }
}
