// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SolanaInstructionWithValue {
    /// The name of the instruction
    #[serde(rename = "name")]
    pub name: String,
    /// The discriminator for the instruction. Acts as a function selector
    #[serde(rename = "discriminator")]
    pub discriminator: Vec<f64>,
    #[serde(rename = "accounts")]
    pub accounts: Vec<models::SolAccountWithValue>,
    /// The arguments of the instruction
    #[serde(rename = "args")]
    pub args: Vec<models::SolParameterWithValue>,
}

impl SolanaInstructionWithValue {
    pub fn new(
        name: String,
        discriminator: Vec<f64>,
        accounts: Vec<models::SolAccountWithValue>,
        args: Vec<models::SolParameterWithValue>,
    ) -> SolanaInstructionWithValue {
        SolanaInstructionWithValue {
            name,
            discriminator,
            accounts,
            args,
        }
    }
}
