// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SolanaSimpleCreateParams {
    /// The name of the token or asset being created.
    #[serde(rename = "name")]
    pub name: String,
    /// The symbol for the token, typically an abbreviated representation.
    #[serde(rename = "symbol")]
    pub symbol: String,
    /// The number of decimal places the token supports (e.g., 9 for typical
    /// Solana tokens).
    #[serde(rename = "decimals")]
    pub decimals: i32,
}

impl SolanaSimpleCreateParams {
    pub fn new(name: String, symbol: String, decimals: i32) -> SolanaSimpleCreateParams {
        SolanaSimpleCreateParams {
            name,
            symbol,
            decimals,
        }
    }
}
