// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// SpeiBasicPaymentInfo : Basic SPEI payment information for Mexican bank
/// transfers
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpeiBasicPaymentInfo {
    /// The CLABE (Clave Bancaria Estandarizada) number for SPEI transfers
    #[serde(rename = "speiClabe")]
    pub spei_clabe: String,
    /// The name associated with the SPEI account
    #[serde(rename = "speiName", skip_serializing_if = "Option::is_none")]
    pub spei_name: Option<String>,
}

impl SpeiBasicPaymentInfo {
    /// Basic SPEI payment information for Mexican bank transfers
    pub fn new(spei_clabe: String) -> SpeiBasicPaymentInfo {
        SpeiBasicPaymentInfo {
            spei_clabe,
            spei_name: None,
        }
    }
}
