// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Tag {
    /// The unique identifier of the tag
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// The tag label
    #[serde(rename = "label")]
    pub label: String,
    /// Description for the tag
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl Tag {
    pub fn new(id: uuid::Uuid, label: String) -> Tag {
        Tag {
            id,
            label,
            description: None,
        }
    }
}
