// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Tag {
    /// The unique identifier of the tag
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// The tag label
    #[serde(rename = "label")]
    pub label: String,
    /// Description for the tag
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The tag color in hex format
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    /// Indication of whether the tag is a protected tag
    #[serde(rename = "isProtected")]
    pub is_protected: bool,
    /// The date and time the tag was last updated
    #[serde(rename = "updatedAt")]
    pub updated_at: f64,
    #[serde(
        rename = "pendingApprovalRequest",
        skip_serializing_if = "Option::is_none"
    )]
    pub pending_approval_request: Option<models::ApprovalRequest>,
}

impl Tag {
    pub fn new(id: uuid::Uuid, label: String, is_protected: bool, updated_at: f64) -> Tag {
        Tag {
            id,
            label,
            description: None,
            color: None,
            is_protected,
            updated_at,
            pending_approval_request: None,
        }
    }
}
