// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TagAttachmentOperationAction {
    #[serde(rename = "ATTACH")]
    Attach,
    #[serde(rename = "DETACH")]
    Detach,
}

impl std::fmt::Display for TagAttachmentOperationAction {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Attach => write!(f, "ATTACH"),
            Self::Detach => write!(f, "DETACH"),
        }
    }
}

impl Default for TagAttachmentOperationAction {
    fn default() -> TagAttachmentOperationAction {
        Self::Attach
    }
}
