// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// TimePeriodConfigV2 : Time period configuration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimePeriodConfigV2 {
    /// Time period in seconds
    #[serde(rename = "seconds")]
    pub seconds: String,
    #[serde(rename = "initiator")]
    pub initiator: models::TimePeriodMatchTypeV2,
    #[serde(rename = "source")]
    pub source: models::TimePeriodMatchTypeV2,
    #[serde(rename = "destination")]
    pub destination: models::TimePeriodMatchTypeV2,
}

impl TimePeriodConfigV2 {
    /// Time period configuration
    pub fn new(
        seconds: String,
        initiator: models::TimePeriodMatchTypeV2,
        source: models::TimePeriodMatchTypeV2,
        destination: models::TimePeriodMatchTypeV2,
    ) -> TimePeriodConfigV2 {
        TimePeriodConfigV2 {
            seconds,
            initiator,
            source,
            destination,
        }
    }
}
