// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// UpdateDraftRequestV2 : Request schema for updating draft with policy types
/// and rules
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateDraftRequestV2 {
    #[serde(rename = "policyTypes")]
    pub policy_types: Vec<models::PolicyTypeV2>,
    /// Array of policy rules
    #[serde(rename = "rules")]
    pub rules: Vec<models::PolicyRuleV2>,
}

impl UpdateDraftRequestV2 {
    /// Request schema for updating draft with policy types and rules
    pub fn new(
        policy_types: Vec<models::PolicyTypeV2>,
        rules: Vec<models::PolicyRuleV2>,
    ) -> UpdateDraftRequestV2 {
        UpdateDraftRequestV2 {
            policy_types,
            rules,
        }
    }
}
