// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsWireDestination {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "address")]
    pub address: models::UsWireAddress,
}

impl UsWireDestination {
    pub fn new(r#type: Type, address: models::UsWireAddress) -> UsWireDestination {
        UsWireDestination { r#type, address }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "US_WIRE")]
    UsWire,
}

impl Default for Type {
    fn default() -> Type {
        Self::UsWire
    }
}
