// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsWireAddress {
    #[serde(rename = "accountHolder")]
    pub account_holder: models::AccountHolderDetails,
    /// Name of the bank.
    #[serde(rename = "bankName", skip_serializing_if = "Option::is_none")]
    pub bank_name: Option<String>,
    /// The bank account number for the wire transfer.
    #[serde(rename = "bankAccountNumber")]
    pub bank_account_number: String,
    /// Routing number identifying the bank account.
    #[serde(rename = "routingNumber")]
    pub routing_number: String,
    /// Address of the bank.
    #[serde(rename = "bankAddress", skip_serializing_if = "Option::is_none")]
    pub bank_address: Option<String>,
}

impl UsWireAddress {
    pub fn new(
        account_holder: models::AccountHolderDetails,
        bank_account_number: String,
        routing_number: String,
    ) -> UsWireAddress {
        UsWireAddress {
            account_holder,
            bank_name: None,
            bank_account_number,
            routing_number,
            bank_address: None,
        }
    }
}
