// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// UsWirePaymentInfo : US Wire payment information for US domestic wire
/// transfers
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsWirePaymentInfo {
    /// The payment rail type for US wire transfers
    #[serde(rename = "rail")]
    pub rail: Rail,
    /// The addressing system used for US wire transfers
    #[serde(rename = "addressingSystem")]
    pub addressing_system: AddressingSystem,
    /// The given name (first name) of the account holder
    #[serde(rename = "accountHolderGivenName")]
    pub account_holder_given_name: String,
    /// The surname (last name) of the account holder
    #[serde(rename = "accountHolderSurname")]
    pub account_holder_surname: String,
    /// The country for the transfer (ISO 3166-1 alpha-2 code)
    #[serde(rename = "country")]
    pub country: String,
    /// The bank account number
    #[serde(rename = "accountNumber")]
    pub account_number: String,
    /// The bank routing number (ABA routing number)
    #[serde(rename = "routingNumber")]
    pub routing_number: String,
    /// The SWIFT/BIC code of the bank
    #[serde(rename = "swiftCode")]
    pub swift_code: String,
    /// The name of the bank
    #[serde(rename = "bankName")]
    pub bank_name: String,
    /// The street address of the bank
    #[serde(rename = "bankAddressLine")]
    pub bank_address_line: String,
    /// The city where the bank is located
    #[serde(rename = "bankAddressCity")]
    pub bank_address_city: String,
    /// The state where the bank is located
    #[serde(rename = "bankAddressState", skip_serializing_if = "Option::is_none")]
    pub bank_address_state: Option<String>,
    /// The country where the bank is located (ISO 3166-1 alpha-2 code)
    #[serde(rename = "bankAddressCountry")]
    pub bank_address_country: String,
    /// The postal code of the bank's address
    #[serde(rename = "bankAddressPostalCode")]
    pub bank_address_postal_code: String,
    /// The branch number of the bank
    #[serde(rename = "branchNumber", skip_serializing_if = "Option::is_none")]
    pub branch_number: Option<String>,
}

impl UsWirePaymentInfo {
    /// US Wire payment information for US domestic wire transfers
    pub fn new(
        rail: Rail,
        addressing_system: AddressingSystem,
        account_holder_given_name: String,
        account_holder_surname: String,
        country: String,
        account_number: String,
        routing_number: String,
        swift_code: String,
        bank_name: String,
        bank_address_line: String,
        bank_address_city: String,
        bank_address_country: String,
        bank_address_postal_code: String,
    ) -> UsWirePaymentInfo {
        UsWirePaymentInfo {
            rail,
            addressing_system,
            account_holder_given_name,
            account_holder_surname,
            country,
            account_number,
            routing_number,
            swift_code,
            bank_name,
            bank_address_line,
            bank_address_city,
            bank_address_state: None,
            bank_address_country,
            bank_address_postal_code,
            branch_number: None,
        }
    }
}
/// The payment rail type for US wire transfers
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Rail {
    #[serde(rename = "US_WIRE")]
    UsWire,
}

impl Default for Rail {
    fn default() -> Rail {
        Self::UsWire
    }
}
/// The addressing system used for US wire transfers
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AddressingSystem {
    #[serde(rename = "ABA")]
    Aba,
}

impl Default for AddressingSystem {
    fn default() -> AddressingSystem {
        Self::Aba
    }
}
