// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VaultAccountTagAttachmentRejectedOperation {
    /// The ID of the vault account
    #[serde(rename = "vaultAccountId")]
    pub vault_account_id: String,
    /// Tag ID
    #[serde(rename = "tagId")]
    pub tag_id: uuid::Uuid,
    #[serde(rename = "action")]
    pub action: models::TagAttachmentOperationAction,
    /// Reason for rejection
    #[serde(rename = "reason")]
    pub reason: Reason,
}

impl VaultAccountTagAttachmentRejectedOperation {
    pub fn new(
        vault_account_id: String,
        tag_id: uuid::Uuid,
        action: models::TagAttachmentOperationAction,
        reason: Reason,
    ) -> VaultAccountTagAttachmentRejectedOperation {
        VaultAccountTagAttachmentRejectedOperation {
            vault_account_id,
            tag_id,
            action,
            reason,
        }
    }
}
/// Reason for rejection
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Reason {
    #[serde(rename = "CAPACITY_EXCEEDED")]
    CapacityExceeded,
    #[serde(rename = "ATTACHMENT_ALREADY_EXISTS")]
    AttachmentAlreadyExists,
    #[serde(rename = "ATTACHMENT_DOES_NOT_EXIST")]
    AttachmentDoesNotExist,
    #[serde(rename = "PENDING_REQUEST_EXISTS")]
    PendingRequestExists,
}

impl Default for Reason {
    fn default() -> Reason {
        Self::CapacityExceeded
    }
}
