// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VaultAccountsTagAttachmentsRequest {
    /// The IDs of the tags to attach
    #[serde(rename = "tagIds")]
    pub tag_ids: Vec<uuid::Uuid>,
    /// The IDs of the vault accounts to attach tags to
    #[serde(rename = "vaultAccountIds")]
    pub vault_account_ids: Vec<String>,
}

impl VaultAccountsTagAttachmentsRequest {
    pub fn new(
        tag_ids: Vec<uuid::Uuid>,
        vault_account_ids: Vec<String>,
    ) -> VaultAccountsTagAttachmentsRequest {
        VaultAccountsTagAttachmentsRequest {
            tag_ids,
            vault_account_ids,
        }
    }
}
