// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VaultAccountTagAttachmentOperation {
    /// The ID of the Vault account
    #[serde(rename = "vaultAccountId")]
    pub vault_account_id: String,
    /// The tag ID
    #[serde(rename = "tagId")]
    pub tag_id: uuid::Uuid,
    #[serde(rename = "action")]
    pub action: models::TagAttachmentOperationAction,
}

impl VaultAccountTagAttachmentOperation {
    pub fn new(
        vault_account_id: String,
        tag_id: uuid::Uuid,
        action: models::TagAttachmentOperationAction,
    ) -> VaultAccountTagAttachmentOperation {
        VaultAccountTagAttachmentOperation {
            vault_account_id,
            tag_id,
            action,
        }
    }
}
