// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VaultAccountsTagAttachmentOperationsResponse {
    /// The operations that were applied
    #[serde(rename = "appliedOperations", skip_serializing_if = "Option::is_none")]
    pub applied_operations: Option<Vec<models::VaultAccountTagAttachmentOperation>>,
    /// The operations that are pending
    #[serde(rename = "pendingOperations", skip_serializing_if = "Option::is_none")]
    pub pending_operations: Option<Vec<models::VaultAccountTagAttachmentPendingOperation>>,
    /// The operations that were rejected
    #[serde(rename = "rejectedOperations", skip_serializing_if = "Option::is_none")]
    pub rejected_operations: Option<Vec<models::VaultAccountTagAttachmentRejectedOperation>>,
}

impl VaultAccountsTagAttachmentOperationsResponse {
    pub fn new() -> VaultAccountsTagAttachmentOperationsResponse {
        VaultAccountsTagAttachmentOperationsResponse {
            applied_operations: None,
            pending_operations: None,
            rejected_operations: None,
        }
    }
}
