permissions:
  contents: read
env:
  FIREBLOCKS_API_KEY: ${{ secrets.FIREBLOCKS_API_KEY }}
  FIREBLOCKS_SECRET: ${{ secrets.FIREBLOCKS_SECRET }}
  FIREBLOCKS_CREATE_TX: "true"
  FIREBLOCKS_CREATE_VAULT: "true"
  RUST_LOG: "info,fireblocks_sdk=debug"
  RUST_BACKTRACE: "1"

on:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: test
jobs:
  integration:
    runs-on: ${{ vars.RUNNER }}
    name: coverage
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ubicloud/rust-cache@v2
        with:
          cache-on-failure: "true"
          cache-all-crates: "true"
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: run tests
        run: cargo test -- --test-threads=1
